#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Megumin-Suite 中文本地化 映射批 4a：故事设置（config + ui）
chips/options.value/legacy/aiNote 为写入值（进 Prompt），一律保留英文。"""

MAPS = {
    # ═══════════════════════════ storyconfig/config.js ═══════════════════════════
    "src/features/storyconfig/config.js": [
        ('label: "Genre"', 'label: "类型"', "once"),
        ('placeholder: "e.g. horror, romance"', 'placeholder: "例如：恐怖、恋爱"', "once"),
        ('hint: "The story\'s genre and the conventions that come with it. Played straight, never commented on."',
         'hint: "故事的类型及其伴随的惯例。认真贯彻，绝不加以评论。"', "once"),
        ('label: "Culture & Setting"', 'label: "文化背景"', "once"),
        ('placeholder: "e.g. Japanese, Western"', 'placeholder: "例如：日本、西方"', "once"),
        ('hint: "The cultural world the story runs on — names, honorifics, food, manners, social rules and the idiom people speak in. Works with era to place the story."',
         'hint: "故事所运行的文化世界——姓名、敬语、饮食、礼仪、社会规则与人们的用语习惯。与时代共同为故事定位。"', "once"),
        ('label: "Era"', 'label: "时代"', "once"),
        ('placeholder: "e.g. 1980s"', 'placeholder: "例如：1980 年代"', "once"),
        ('hint: "The year or period the world runs on."', 'hint: "世界所运行的年份或时期。"', "once"),
        ('label: "Point of View"', 'label: "视角"', "once"),
        ('hint: "Narrative person and where the camera sits. Never loosens the {{user}} boundary."',
         'hint: "叙事人称与镜头所在。绝不放松 {{user}} 的边界。"', "once"),
        ('customPlaceholder: "e.g. third limited, sitting behind Maya\'s eyes"',
         'customPlaceholder: "例如：第三人称限知，坐在 Maya 的眼睛后面"', "once"),
        ('{ label: "second person on {{user}}", legacy:',
         '{ label: "第二人称（指向 {{user}}）", legacy:', "once"),
        ('{ label: "third limited", legacy:', '{ label: "第三人称限知", legacy:', "once"),
        ('{ label: "third limited following one character", legacy:',
         '{ label: "第三人称限知（跟随单一角色）", legacy:', "once"),
        ('{ label: "third omniscient", legacy:', '{ label: "第三人称全知", legacy:', "once"),
        ('{ label: "first person", legacy:', '{ label: "第一人称", legacy:', "once"),
        ('{ label: "roving", legacy:', '{ label: "游移", legacy:', "once"),
        ('label: "Focus"', 'label: "焦点"', "once"),
        ('placeholder: "e.g. the camera follows Maya"', 'placeholder: "例如：镜头跟随 Maya"', "once"),
        ('hint: "Whose story this is, if the camera should favour someone other than {{user}}. Name them."',
         'hint: "如果镜头应偏爱 {{user}} 之外的某人，这是谁的故事。写出他们的名字。"', "once"),
        ('label: "Narration Tone"', 'label: "旁白基调"', "once"),
        ('placeholder: "e.g. bleak, absurd"', 'placeholder: "例如：阴郁、荒诞"', "once"),
        ('hint: "The mood that sits over the whole story, whatever is happening in a given scene."',
         'hint: "笼罩整个故事的情绪基调，无论某个场景中正发生什么。"', "once"),
        ('label: "Narrator Presence"', 'label: "叙述者存在感"', "once"),
        ('customPlaceholder: "e.g. heavy. comment on everything"', 'customPlaceholder: "例如：存在感强，评论一切"', "once"),
        ('hint: "How visible the narrator\'s attitude is. Light is your preset default."',
         'hint: "叙述者态度的可见程度。轻盈是你的预设默认。"', "once"),
        ('defaultLabel: "light"', 'defaultLabel: "轻盈"', "once"),
        ('{ label: "invisible", legacy:', '{ label: "隐于幕后", legacy:', "once"),
        ('{ label: "heavy", legacy:', '{ label: "存在感强", legacy:', "once"),
        ('label: "NPC Speech Style"', 'label: "NPC 说话风格"', "once"),
        ('placeholder: "e.g. 1980s poetic"', 'placeholder: "例如：1980 年代诗性"', "once"),
        ('hint: "Override how the NPCs sound."', 'hint: "覆盖 NPC 的说话方式。"', "once"),
        ('label: "NPC Disposition"', 'label: "NPC 态度"', "once"),
        ('customPlaceholder: "e.g. cold. the NPCs don\'t like {{user}}"',
         'customPlaceholder: "例如：冷淡。NPC 们不喜欢 {{user}}"', "once"),
        ('hint: "How the cast feels about {{user}} before they earn anything else. Ordinary is your preset default."',
         'hint: "在角色们赢得任何东西之前，他们对 {{user}} 的态度。普通是你的预设默认。"', "once"),
        ('defaultLabel: "ordinary"', 'defaultLabel: "普通"', "once"),
        ('{ label: "warm", legacy:', '{ label: "友善", legacy:', "once"),
        ('{ label: "wary", legacy:', '{ label: "警惕", legacy:', "once"),
        ('{ label: "cold", legacy:', '{ label: "冷淡", legacy:', "once"),
        ('{ label: "hostile", legacy:', '{ label: "敌对", legacy:', "once"),
        ('label: "Difficulty"', 'label: "难度"', "once"),
        ('customPlaceholder: "e.g. hard. the world is against {{user}}"',
         'customPlaceholder: "例如：困难。世界与 {{user}} 为敌"', "once"),
        ('hint: "How hard the world pushes back on what {{user}} attempts. Realistic is your preset default."',
         'hint: "世界对 {{user}} 尝试之事的回推强度。真实是你的预设默认。"', "once"),
        ('defaultLabel: "realistic"', 'defaultLabel: "真实"', "once"),
        ('{ label: "forgiving", legacy:', '{ label: "宽松", legacy:', "once"),
        ('{ label: "harsh", legacy:', '{ label: "严酷", legacy:', "once"),
        ('label: "Friction"', 'label: "摩擦"', "once"),
        ('customPlaceholder: "e.g. high. trouble is always around the corner"',
         'customPlaceholder: "例如：高。麻烦总在转角处"', "once"),
        ('hint: "How often trouble arrives. Normal is your preset default."',
         'hint: "麻烦出现的频率。正常是你的预设默认。"', "once"),
        ('defaultLabel: "normal"', 'defaultLabel: "正常"', "once"),
        ('{ label: "low", legacy:', '{ label: "低", legacy:', "once"),
        ('{ label: "high", legacy:', '{ label: "高", legacy:', "once"),
        ('label: "Explicitness"', 'label: "露骨程度"', "once"),
        ('customPlaceholder: "e.g. graphic. give details"', 'customPlaceholder: "例如：露骨，给出细节"', "once"),
        ('hint: "How far scenes go and how directly they are written."',
         'hint: "场景进行到多深入，以及写作有多直接。"', "once"),
        ('{ label: "fade to black", legacy:', '{ label: "淡出处理", legacy:', "once"),
        ('{ label: "plain", legacy:', '{ label: "直白", legacy:', "once"),
        ('{ label: "graphic", legacy:', '{ label: "露骨", legacy:', "once"),
        ('label: "Pace"', 'label: "节奏"', "once"),
        ('customPlaceholder: "e.g. steady, but skip anything that isn\'t a real beat"',
         'customPlaceholder: "例如：平稳，但跳过任何不是真正节拍的内容"', "once"),
        ('hint: "How fast story time moves."', 'hint: "故事时间推进的速度。"', "once"),
        ('{ label: "slow burn", legacy:', '{ label: "慢热", legacy:', "once"),
        ('{ label: "steady", legacy:', '{ label: "平稳", legacy:', "once"),
        ('{ label: "fast", legacy:', '{ label: "快速", legacy:', "once"),
        ('label: "Length"', 'label: "篇幅"', "once"),
        ('customPlaceholder: "e.g. around 300 words, longer when a scene earns it"',
         'customPlaceholder: "例如：约 300 词，场景值得时更长"', "once"),
        ('hint: "How long each reply should run."', 'hint: "每条回复应有的长度。"', "once"),
        ('{ label: "flexible", legacy:', '{ label: "灵活", legacy:', "once"),
        ('{ label: "250–350 words", legacy:', '{ label: "250–350 词", legacy:', "once"),
        ('{ label: "450–550 words", legacy:', '{ label: "450–550 词", legacy:', "once"),
        ('{ label: "minimum 900 words", legacy:', '{ label: "至少 900 词", legacy:', "once"),
        ('label: "Notes"', 'label: "备注"', "once"),
        ('placeholder: "e.g. never let Maya win"', 'placeholder: "例如：永远不要让 Maya 赢"', "once"),
        ('hint: "Any standing instruction that doesn\'t fit a field above."',
         'hint: "任何不适合上面某个字段的常驻指令。"', "once"),
        ('id: "cfg_grimdark", name: "Grimdark Survival"', 'id: "cfg_grimdark", name: "黑暗生存"', "once"),
        ('id: "cfg_cozy", name: "Cozy Slice of Life"', 'id: "cfg_cozy", name: "温馨日常"', "once"),
        ('id: "cfg_noir", name: "Noir Mystery"', 'id: "cfg_noir", name: "黑色悬疑"', "once"),
        ('id: "cfg_horror", name: "Slow Dread Horror"', 'id: "cfg_horror", name: "缓释恐怖"', "once"),
        ('id: "cfg_romance", name: "Slow Burn Romance"', 'id: "cfg_romance", name: "慢热恋爱"', "once"),
    ],
    # ═══════════════════════════ storyconfig/ui.js ═══════════════════════════
    "src/features/storyconfig/ui.js": [
        ("Share Story Config with every character", "与每个角色共享故事设置", "once"),
        ("These fields are copied to every character along with the rest of this tab.",
         "这些字段会与此标签页的其余设置一起复制到每个角色。", "once"),
        ("The engine and CoT choice still go everywhere. These fields stay with this character.",
         "引擎与思维链的选择仍会全局生效。这些字段则留在此角色。", "once"),
        ("Only applies once this tab's <strong>Global</strong> switch is on",
         "仅在此标签页的 <strong>全局</strong> 开关开启后生效", "once"),
        ('"On"', '"开"', "all"),
        ('"Off"', '"关"', "all"),
        ('toastr.info("Saved. It takes effect when this tab\'s Global switch is on."',
         'toastr.info("已保存。此标签页的全局开关开启后生效。"', "once"),
        ('"Story Config now travels with the other settings on this tab."',
         '"故事设置现在与此标签页的其他设置一起全局生效。"', "once"),
        ('"Story Config stays with this character now."', '"故事设置现在只保留在此角色。"', "once"),
        ("> Story Config</h3>", "> 故事设置</h3>", "once"),
        ('Standing settings for the whole story. Anything left on preset default is left to your preset.',
         '整个故事的常驻设置。保留在预设默认值的项目将交由你的预设处理。', "once"),
        (">Load a config preset…</option>", ">加载配置预设…</option>", "once"),
        ('<optgroup label="Built-in">', '<optgroup label="内置">', "once"),
        ('<optgroup label="My Presets">', '<optgroup label="我的预设">', "once"),
        ("> Load</button>", "> 加载</button>", "once"),
        ("> Save Current</button>", "> 保存当前</button>", "once"),
        ("> Reset All</button>", "> 全部重置</button>", "once"),
        ('"Pick a preset first."', '"请先选择一个预设。"', "all"),
        ('`Loaded "${p.name}".`', '`已加载“${p.name}”。`', "once"),
        ('prompt("Name this config preset:")', 'prompt("为此配置预设命名：")', "once"),
        ('`Saved "${name.trim()}".`', '`已保存“${name.trim()}”。`', "once"),
        ('"Built-in presets can\'t be deleted."', '"内置预设无法删除。"', "once"),
        ('`Delete the preset "${p.name}"?`', '`删除预设“${p.name}”？`', "once"),
        ('"Preset deleted."', '"预设已删除。"', "once"),
        ('"Set every setting back to preset default?"', '"将每个设置都恢复为预设默认值？"', "once"),
        ('Preset default — ${f.defaultLabel}', '预设默认 — ${f.defaultLabel}', "all"),
        ('>Write my own…</option>', '>自己编写…</option>', "once"),
        ('placeholder="${escapeHtmlAttr(f.customPlaceholder || `Write it your own way`)}"',
         'placeholder="${escapeHtmlAttr(f.customPlaceholder || `用自己的方式编写`)}"', "once"),
        ('<h2>Writing Style</h2>', '<h2>写作风格</h2>', "once"),
        ('Pick the prose voice the story is told in.', '选择故事叙述所用的文字声音。', "once"),
        ("? 'No Style' : activeStyleName", "? '无风格' : activeStyleName", "once"),
        ("> DN Ratio</span>", "> DN 比例</span>", "once"),
        (">Narration</div>", ">旁白</div>", "once"),
        (">Dialogue</div>", ">对话</div>", "once"),
        ("&#9664; more narration", "&#9664; 更多旁白", "once"),
        ("more dialogue &#9654;", "更多对话 &#9654;", "once"),
        ("> No Style (Off)</span>", "> 无风格（关闭）</span>", "once"),
        ('"Modern Engines require a narrative style directive."',
         '"现代引擎需要叙事风格指令。"', "once"),
        ("> Precooked</span>", "> 预制</span>", "once"),
        ("> My Library</span>", "> 我的文库</span>", "once"),
        ("> AI Generators</span>", "> AI 生成器</span>", "once"),
        ("> Precooked Styles</h3>", "> 预制风格</h3>", "once"),
        ("> Edit as Custom</button>", "> 按自定义编辑</button>", "once"),
        ("> Create New Style</div>", "> 创建新风格</div>", "once"),
        ("Custom AI generated style.", "自定义 AI 生成的风格。", "once"),
        ("> Edit</button>", "> 编辑</button>", "once"),
        ('`Delete "${style.name}"?`', '`删除“${style.name}”？`', "once"),
        ('"Rule Regenerated!"', '"规则已重新生成！"', "once"),
        ("</i> Generate This Style", "</i> 生成此风格", "once"),
        ("</i> Generating...`", "</i> 正在生成...`", "once"),
        ('`${tpl.name} Added!`', '`已添加 ${tpl.name}！`', "once"),
        ("disabled selected>✨ Load a Pre-configured Template...</option>",
         "disabled selected>✨ 加载预配置模板...</option>", "once"),
        ('placeholder="Name your style…"', 'placeholder="为风格命名…"', "once"),
        ("</i> Save", "</i> 保存", "once"),
        ("</i> Back", "</i> 返回", "once"),
        ('`${chosenTpl.name} loaded!`', '`已加载 ${chosenTpl.name}！`', "once"),
        (">AI Author Matches</span>", ">AI 作者匹配</span>", "once"),
        ("</i> Generate Insights", "</i> 生成洞察", "all"),
        ('placeholder="Custom directives or inspiration notes…"', 'placeholder="自定义指令或灵感笔记…"', "once"),
        (">Generated Rule</span>", ">生成的规则</span>", "once"),
        ("</i> Generate Writing Rule", "</i> 生成写作规则", "all"),
        ('placeholder="Select tags above and click Generate…"', 'placeholder="先选择上方标签，再点击生成…"', "once"),
        ("After generating or editing your rule, hit <strong>Save</strong> in the toolbar above to apply it to your library.",
         "生成或编辑规则后，点击上方工具栏的 <strong>保存</strong> 将其应用到你的文库。", "once"),
        ('"Unnamed Style"', '"未命名风格"', "once"),
        ('`Saved "${currentStyle.name}"`', '`已保存“${currentStyle.name}”`', "once"),
        ('"Open a chat or group first so I can read the context!"',
         '"请先打开一个聊天或群组，以便我读取上下文！"', "once"),
        ("</i> Brainstorming...`", "</i> 头脑风暴中...`", "once"),
        ('`Generated ${aiTagsTemp.length} insights!`', '`已生成 ${aiTagsTemp.length} 条洞察！`', "once"),
        ('"Select tags first!"', '"请先选择标签！"', "once"),
        ("</i> Finalizing...`", "</i> 收尾中...`", "once"),
        ('"Live AI Rule Generated!"', '"实时 AI 规则已生成！"', "once"),
    ],
}
