#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Megumin-Suite 中文本地化 映射批 5b：slots label / SLOT_GROUPS / directStyles / image_data
约束：slots key/trigger 不动；directStyles id 不动；RESOLUTIONS 数字保留。"""

MAPS = {
    # ═══════════════════════════ data/slots.js ═══════════════════════════
    "data/slots.js": [
        ('label: "Prompt 1"', 'label: "提示词 1"', "once"),
        ('label: "Prompt 2"', 'label: "提示词 2"', "once"),
        ('label: "Prompt 3"', 'label: "提示词 3"', "once"),
        ('label: "Prompt 4"', 'label: "提示词 4"', "once"),
        ('label: "Prompt 5"', 'label: "提示词 5"', "once"),
        ('label: "Prompt 6"', 'label: "提示词 6"', "once"),
        ('label: "Personality"', 'label: "性格"', "once"),
        ('label: "Model Acknowledgement 1"', 'label: "模型确认 1"', "once"),
        ('label: "Model Acknowledgement 2"', 'label: "模型确认 2"', "once"),
        ('label: "Chain of Thought"', 'label: "思维链"', "once"),
        ('label: "Prefill"', 'label: "预填"', "once"),
        ('label: "Thinking Tags"', 'label: "思考标签"', "once"),
        ('label: "Death System"', 'label: "死亡系统"', "once"),
        ('label: "Combat System"', 'label: "战斗系统"', "once"),
        ('label: "Immersive HTML"', 'label: "沉浸式 HTML"', "once"),
        ('label: "Dice"', 'label: "骰子"', "once"),
        ('label: "Player only (3 rolls)"', 'label: "仅玩家（3 次掷骰）"', "once"),
        ('label: "Everyone (6 rolls)"', 'label: "所有人（6 次掷骰）"', "once"),
        ('label: "Never Write For {{user}}"', 'label: "绝不代写 {{user}}"', "once"),
        ('label: "Direct Language"', 'label: "直白语言"', "once"),
        ('label: "Dialogue / Narration Tags"', 'label: "对话 / 旁白标签"', "once"),
        ('label: "Dialogue Colours"', 'label: "对话配色"', "once"),
        ('label: "Onomatopoeia"', 'label: "拟声词"', "once"),
        ('label: "Dialogue / Narration Ratio"', 'label: "对话 / 旁白比例"', "once"),
        ('label: "Ban List (your additions)"', 'label: "屏蔽列表（你的添加项）"', "once"),
        ('label: "World State Block"', 'label: "世界状态信息块"', "once"),
        ('label: "Choice Block"', 'label: "选择信息块"', "once"),
        ('label: "MVU Variables"', 'label: "MVU 变量"', "once"),
        ('label: "NPC Inner Chatter"', 'label: "NPC 内心独白"', "once"),
        ('label: "Default"', 'label: "默认"', "once"),
        ('label: "Simple"', 'label: "简单"', "once"),
        ('label: "Story Tracker"', 'label: "故事追踪器"', "once"),
        ('label: "Language Rule"', 'label: "语言规则"', "once"),
        ('label: "Your Pronouns"', 'label: "你的代词"', "once"),
        ('label: "Word Count"', 'label: "词数"', "once"),
        ('label: "Story Config"', 'label: "故事设置"', "once"),
        ('label: "Output Blocks"', 'label: "输出信息块"', "all"),
        ('label: "Long-term Memory"', 'label: "长期记忆"', "once"),
        ('label: "Short-term Memory"', 'label: "短期记忆"', "once"),
        ('label: "NPC List"', 'label: "NPC 列表"', "once"),
        ('label: "NPC Dossier Rules"', 'label: "NPC 档案规则"', "once"),
        ('label: "Organic NPCs & Events"', 'label: "自然 NPC 与事件"', "once"),
        ('label: "Story Plan"', 'label: "故事规划"', "once"),
        ('label: "Image Rules"', 'label: "图像规则"', "once"),
        ('label: "Narration Style"', 'label: "旁白风格"', "once"),
        ('label: "OOC Protocol"', 'label: "OOC 协议"', "once"),
        ('label: "Control Protocol"', 'label: "控制协议"', "once"),
        ('picker: { label: "Load from a chain-of-thought"', 'picker: { label: "从思维链加载"', "all"),
        # SLOT_GROUPS
        ('{ id: "engine", label: "The Engine\'s Own Rules"', '{ id: "engine", label: "引擎自身规则"', "once"),
        ('{ id: "reasoning", label: "Reasoning"', '{ id: "reasoning", label: "推理"', "once"),
        ('{ id: "systems", label: "Systems"', '{ id: "systems", label: "系统"', "once"),
        ('{ id: "format", label: "Formatting"', '{ id: "format", label: "格式"', "once"),
        ('{ id: "blocks", label: "Output Blocks"', '{ id: "blocks", label: "输出信息块"', "once"),
        ('{ id: "global", label: "Built From Your Settings"', '{ id: "global", label: "由你的设置构建"', "once"),
        ('{ id: "live", label: "Filled In Automatically"', '{ id: "live", label: "自动填充"', "once"),
    ],
    # ═══════════════════════════ data/directStyles.js ═══════════════════════════
    "data/directStyles.js": [
        ('name: "Simple & Direct"', 'name: "简洁直接"', "once"),
        ('desc: "Focuses on physical actions and chronological events. Highly efficient."',
         'desc: "聚焦身体动作与时间顺序事件。非常高效。"', "once"),
        ('name: "Descriptive & Spatial"', 'name: "描述与空间"', "once"),
        ('desc: "Focuses on the physical parameters and sensory data of the environment."',
         'desc: "聚焦环境的物理参数与感官数据。"', "once"),
        ('name: "Dialogue-Centric"', 'name: "对话中心"', "once"),
        ('desc: "Prioritizes spoken words and subtle physical cues between speech."',
         'desc: "优先呈现话语本身与对话间的细微肢体信号。"', "once"),
        ('name: "Clinical & Objective"', 'name: "临床客观"', "once"),
        ('desc: "Cold, precise, and completely detached narration. No emotional assumptions."',
         'desc: "冷静、精确、完全超然的旁白。不做任何情绪假设。"', "once"),
        ('name: "Sensory-Rich"', 'name: "感官丰富"', "once"),
        ('desc: "Grounds the scene heavily in the five senses."',
         'desc: "让场景深深扎根于五感。"', "once"),
        ('desc: "The register shifts scene to scene and never repeats the last turn\'s temperature."',
         'desc: "语域随场景切换，且绝不重复上一回合的温度。"', "once"),
        ('desc: "Find the scene\'s temperature and commit; let it change from inside the scene."',
         'desc: "找到场景的温度并坚持；让它从场景内部自然变化。"', "once"),
        ('desc: "The V9 Default the best of both worlds."',
         'desc: "V9 默认——两全其美。"', "once"),
        ('desc: "The V9 Lite Default."', 'desc: "V9 Lite 默认。"', "once"),
        ('desc: "Witty, opinionated observer. Dry, occasionally judgmental, quietly amused."',
         'desc: "机敏、有主见的观察者。冷幽默，偶尔挑剔，暗自觉得有趣。"', "all"),
        ('desc: "Grounded, cinematic, patient. Scales with scene density and matches prose to content."',
         'desc: "扎实、电影化、耐心。随场景密度伸缩，让文风贴合内容。"', "once"),
        ('desc: "Gentle, cinematic, patient. Scales with scene density and matches prose to content."',
         'desc: "温和、电影化、耐心。随场景密度伸缩，让文风贴合内容。"', "once"),
        ('desc: "Grounded, cinematic, patient. Describes what the camera would see and what the mic would catch."',
         'desc: "扎实、电影化、耐心。描写镜头会看到、话筒会捕捉到的东西。"', "once"),
    ],
    # ═══════════════════════════ data/image_data.js ═══════════════════════════
    "data/image_data.js": [
        ('desc: "Positive Prompt (Text)"', 'desc: "正面提示词（文本）"', "once"),
        ('desc: "Negative Prompt (Text)"', 'desc: "负面提示词（文本）"', "once"),
        ('desc: "Seed (Integer)"', 'desc: "种子（整数）"', "once"),
        ('desc: "Sampling Steps (Integer)"', 'desc: "采样步数（整数）"', "once"),
        ('desc: "CFG Scale (Float)"', 'desc: "CFG 比例（浮点数）"', "once"),
        ('desc: "Denoise Strength (Float)"', 'desc: "去噪强度（浮点数）"', "once"),
        ('desc: "CLIP Skip (Integer)"', 'desc: "CLIP 跳过（整数）"', "once"),
        ('desc: "Checkpoint Name"', 'desc: "检查点名称"', "once"),
        ('desc: "Sampler Name"', 'desc: "采样器名称"', "once"),
        ('desc: "Image Width (px)"', 'desc: "图像宽度（px）"', "once"),
        ('desc: "Image Height (px)"', 'desc: "图像高度（px）"', "once"),
        ('desc: "LoRA 1 Filename"', 'desc: "LoRA 1 文件名"', "once"),
        ('desc: "LoRA 1 Weight (Float)"', 'desc: "LoRA 1 权重（浮点数）"', "once"),
        ('desc: "LoRA 2 Filename"', 'desc: "LoRA 2 文件名"', "once"),
        ('desc: "LoRA 2 Weight (Float)"', 'desc: "LoRA 2 权重（浮点数）"', "once"),
        ('desc: "LoRA 3 Filename"', 'desc: "LoRA 3 文件名"', "once"),
        ('desc: "LoRA 3 Weight (Float)"', 'desc: "LoRA 3 权重（浮点数）"', "once"),
        ('desc: "LoRA 4 Filename"', 'desc: "LoRA 4 文件名"', "once"),
        ('desc: "LoRA 4 Weight (Float)"', 'desc: "LoRA 4 权重（浮点数）"', "once"),
        # RESOLUTIONS label（数字与比例保留，翻译括号内说明）
        ('label: "1024 x 1024 (SDXL 1:1)"', 'label: "1024 x 1024（SDXL 1:1）"', "once"),
        ('label: "1152 x 896 (SDXL Landscape)"', 'label: "1152 x 896（SDXL 横版）"', "once"),
        ('label: "896 x 1152 (SDXL Portrait)"', 'label: "896 x 1152（SDXL 竖版）"', "once"),
        ('label: "1216 x 832 (SDXL Landscape)"', 'label: "1216 x 832（SDXL 横版）"', "once"),
        ('label: "832 x 1216 (SDXL Portrait)"', 'label: "832 x 1216（SDXL 竖版）"', "once"),
        ('label: "1344 x 768 (SDXL Landscape)"', 'label: "1344 x 768（SDXL 横版）"', "once"),
        ('label: "768 x 1344 (SDXL Portrait)"', 'label: "768 x 1344（SDXL 竖版）"', "once"),
        ('label: "512 x 512 (SD 1.5 1:1)"', 'label: "512 x 512（SD 1.5 1:1）"', "once"),
        ('label: "768 x 512 (SD 1.5 Landscape)"', 'label: "768 x 512（SD 1.5 横版）"', "once"),
        ('label: "512 x 768 (SD 1.5 Portrait)"', 'label: "512 x 768（SD 1.5 竖版）"', "once"),
    ],
}
