#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Megumin-Suite 中文本地化 映射批 4c：NPC 图鉴 + 信息块"""

MAPS = {
    # ═══════════════════════════ npc/ui.js ═══════════════════════════
    "src/features/npc/ui.js": [
        ('<h2>NPCs Bank</h2>', '<h2>NPC 图鉴</h2>', "once"),
        ("Automatically extract and track significant NPCs in the story.",
         "自动提取并追踪故事中的重要 NPC。", "once"),
        ("? 'Enabled' : 'Disabled'}", "? '已启用' : '已禁用'}", "once"),
        ("> Enable NPC Bank</div>", "> 启用 NPC 图鉴</div>", "once"),
        ("> Injection Settings</div>", "> 注入设置</div>", "once"),
        ("OOC Trigger <i class=\"fa-solid fa-circle-question\"", "OOC 触发 <i class=\"fa-solid fa-circle-question\"", "once"),
        ('title="When ON, Dossier Template ONLY injects if \'NPC\' or \'dossier\' is in your latest message."',
         'title="开启时，仅当你的最新消息中包含“NPC”或“dossier”时才会注入档案模板。"', "once"),
        (">Manual Extract</span>", ">手动提取</span>", "once"),
        ("Send Portraits <i class=\"fa-solid fa-circle-question\"", "发送头像 <i class=\"fa-solid fa-circle-question\"", "once"),
        ('title="If an injected NPC has a portrait, send the image to the AI vision model."',
         'title="如果注入的 NPC 有头像，将该图像发送给 AI 视觉模型。"', "once"),
        (">Multimodal</span>", ">多模态</span>", "once"),
        ("Max Injections <i class=\"fa-solid fa-circle-question\"", "最大注入数 <i class=\"fa-solid fa-circle-question\"", "once"),
        ('title="Limit how many NPCs are injected into the prompt at once."',
         'title="限制一次注入到提示词中的 NPC 数量。"', "once"),
        ("</i> Ignore List (Do Not Extract)</div>", "</i> 忽略列表（不提取）</div>", "once"),
        ('placeholder="e.g. Fluffy, Guards, The Bartender..."', 'placeholder="例如：Fluffy、守卫、酒保..."', "once"),
        ("> Scanner Settings</div>", "> 扫描设置</div>", "once"),
        (">Scan Depth (Messages)</div>", ">扫描深度（消息数）</div>", "once"),
        ("Note: High numbers consume massive context limits and API tokens!",
         "注意：较高的数字会消耗大量上下文与 API token！", "once"),
        ("> Saved NPCs <span", "> 已保存的 NPC <span", "once"),
        ('title="Import NPCs"', 'title="导入 NPC"', "once"),
        ('title="Export All NPCs"', 'title="导出全部 NPC"', "once"),
        ('title="Create an NPC by hand"', 'title="手动创建 NPC"', "once"),
        ("</i> Add NPC</button>", "</i> 添加 NPC</button>", "once"),
        ("</i> Scan Story</button>", "</i> 扫描故事</button>", "once"),
        ("</i> Clear All</button>", "</i> 全部清空</button>", "once"),
        ('title: "Advanced: Edit NPC Prompts"', 'title: "高级：编辑 NPC 提示词"', "once"),
        ('"Invalid NPC Bank file format."', '"NPC 图鉴文件格式无效。"', "once"),
        ('"Do you want to merge imported NPCs with your existing ones? (Click \'Cancel\' to overwrite)"',
         '"是否将导入的 NPC 与现有 NPC 合并？（点击“取消”则覆盖）"', "once"),
        ('"NPCs imported successfully!"', '"NPC 导入成功！"', "once"),
        ('"Failed to parse JSON file."', '"解析 JSON 文件失败。"', "once"),
        ('prompt("Name for the new NPC:", "")', 'prompt("为新 NPC 命名：", "")', "once"),
        ('`"${trimmed}" is already in the bank.`', '`“${trimmed}”已在图鉴中。`', "once"),
        ('`"${trimmed}" added. Open the card to fill in the details.`',
         '`“${trimmed}”已添加。打开卡片填写详情。`', "once"),
        ('"Are you sure you want to delete all saved NPCs? This cannot be undone."',
         '"确定要删除所有已保存的 NPC 吗？此操作无法撤销。"', "once"),
        ('"Not enough chat history to scan."', '"聊天历史不足，无法扫描。"', "once"),
        ("</i> Scanning...`", "</i> 扫描中...`", "once"),
        ('`Found and added ${addedCount} new NPC(s)!`', '`发现并添加了 ${addedCount} 个新 NPC！`', "once"),
        ('"No new significant NPCs found in the story."', '"故事中没有发现新的重要 NPC。"', "once"),
        ('"Failed to scan story for NPCs."', '"扫描故事中的 NPC 失败。"', "once"),
        ("> Dossier Fields</span>", "> 档案字段</span>", "once"),
        (">Every field has been removed. Add one below, or reset to the defaults.</div>",
         ">所有字段都已被移除。在下方添加一个，或重置为默认值。</div>", "once"),
        ('placeholder="Field name"', 'placeholder="字段名"', "once"),
        ('title="Lasting: describes their ongoing life, not this scene."',
         'title="持续型：描述他们的长期生活，而非当前场景。"', "once"),
        ("? \"Lasting\" : \"Current\"}", "? \"持续型\" : \"当前\"}", "once"),
        ('title="Updatable: an &lt;NPC_Update&gt; block may change this field later."',
         'title="可更新：<NPC_Update> 信息块之后可能更改此字段。"', "once"),
        ("? \"Updatable\" : \"Fixed\"}", "? \"可更新\" : \"固定\"}", "once"),
        ('title="Move up"', 'title="上移"', "once"),
        ('title="Remove this field"', 'title="移除此字段"', "once"),
        ('placeholder="What to tell the AI to put here"', 'placeholder="告诉 AI 在此处填写什么"', "once"),
        ("</i> Add field</button>", "</i> 添加字段</button>", "once"),
        ('"New field"', '"新字段"', "once"),
        ("</i> Reset fields</button>", "</i> 重置字段</button>", "once"),
        ('"Dossier fields reset to defaults."', '"档案字段已重置为默认值。"', "once"),
        (">No NPCs saved yet. The AI will add them automatically when significant NPCs are introduced.</div>",
         ">尚无已保存的 NPC。当故事引入重要 NPC 时，AI 会自动添加。</div>", "once"),
        ('title="Edit Name"', 'title="编辑名字"', "once"),
        ('title="Edit age, sex and orientation"', 'title="编辑年龄、性别与取向"', "once"),
        ('title="If enabled, hides the text dossier from the AI to save tokens, but still sends Image Tags to ComfyUI."',
         'title="启用后，向 AI 隐藏文本档案以节省 token，但仍会向 ComfyUI 发送图像标签。"', "once"),
        (">Image Tags Only</span>", ">仅图像标签</span>", "once"),
        ('title="Re-read the story and update this NPC\'s changeable fields now"',
         'title="重新阅读故事并立即更新此 NPC 的可变字段"', "once"),
        ('title="Export NPC"', 'title="导出 NPC"', "once"),
        ('title="Delete NPC"', 'title="删除 NPC"', "once"),
        ('title="Upload Image"', 'title="上传图像"', "once"),
        ("</i> Upload", "</i> 上传", "once"),
        ('title="Generate with ComfyUI"', 'title="使用 ComfyUI 生成"', "once"),
        ("</i> Generate", "</i> 生成", "once"),
        ('"Image Tags Only enabled. Text dossier will be hidden from AI."',
         '"已启用仅图像标签。文本档案将对 AI 隐藏。"', "once"),
        ('"Full Sync enabled. Text dossier will be sent to AI."',
         '"已启用完整同步。文本档案将发送给 AI。"', "once"),
        ('prompt("Enter new name for this NPC:", currentName)', 'prompt("为此 NPC 输入新名字：", currentName)', "once"),
        ('{ okButton: "Save", cancelButton: "Cancel" }', '{ okButton: "保存", cancelButton: "取消" }', "once"),
        ('"No field is marked Updatable, so there is nothing an update could change."',
         '"没有字段标记为可更新，因此更新不会改变任何内容。"', "once"),
        ('`Nothing on ${target.name}\'s record has changed.`', '`${target.name} 的记录没有任何变化。`', "all"),
        ('`Megumin Suite — ${target.name} updated`', '`Megumin Suite — ${target.name} 已更新`', "once"),
        ('`Could not update ${target.name}.`', '`无法更新 ${target.name}。`', "once"),
        ('Delete ${localProfile.npcBank.npcs[i]?.name || "this NPC"}?',
         '删除 ${localProfile.npcBank.npcs[i]?.name || "此 NPC"}？', "once"),
        ('"Portrait uploaded!"', '"头像已上传！"', "once"),
    ],
    # ═══════════════════════════ blocks/ui.js ═══════════════════════════
    "src/features/blocks/ui.js": [
        ('title="You edited this in Dev Mode. It no longer uses the built-in text."',
         'title="你在开发模式中编辑过此内容。它不再使用内置文本。"', "once"),
        (">edited</span>", ">已编辑</span>", "once"),
        ('<h2>Blocks</h2>', '<h2>信息块</h2>', "once"),
        ("Everything in this list is sent as one master block at the end of the reply, and drawn in the chat as one collapsible card.",
         "此列表中的所有内容将作为一条主信息块在回复末尾发送，并在聊天中以一张可折叠卡片呈现。", "once"),
        ('${inStack.length} in block', '信息块中 ${inStack.length} 个', "once"),
        ("> Inside the master block</div>", "> 主信息块内</div>", "once"),
        (">Nothing here yet. Add a block from the right.</div>", ">这里还没有内容。从右侧添加一个信息块。</div>", "once"),
        (">custom</span>", ">自定义</span>", "once"),
        ("— its feature is switched off, so it is not sent", "— 其功能已关闭，因此不会发送", "once"),
        (">Compact mode</div>", ">紧凑模式</div>", "once"),
        ("Sends a shorter World State on most turns to save tokens.",
         "在大多数回合发送更简短的世界状态以节省 token。", "once"),
        (">Full state every</div>", ">完整状态每</div>", "once"),
        ("How often the complete template comes back.", "完整模板每隔多久回归一次。", "once"),
        (">replies</span>", ">条回复</span>", "once"),
        ("> Add a block</div>", "> 添加信息块</div>", "once"),
        (">Every block is already in.</div>", ">所有信息块都已加入。</div>", "once"),
        ("> Create custom block</button>", "> 创建自定义信息块</button>", "once"),
        ("> Preview</div>", "> 预览</div>", "once"),
        ("This is the card the chat draws. Click a header to fold it.",
         "这是聊天渲染出的卡片。点击标题可折叠。", "once"),
        (">Fields</div>", ">字段</div>", "once"),
        ("What the AI is asked to track${def.id === \"bonds\" ? \" for each NPC\" : \"\"}. Every field costs tokens on every reply.",
         "要求 AI 追踪的内容${def.id === \"bonds\" ? \" 针对每个 NPC\" : \"\"}。每个字段都会在每条回复中消耗 token。", "once"),
        ('placeholder="Name"', 'placeholder="名称"', "once"),
        ('title="Maximum"', 'title="最大值"', "once"),
        ('title="Starting value"', 'title="起始值"', "once"),
        ("</i> Add field</button>", "</i> 添加字段</button>", "once"),
        ('"New field"', '"新字段"', "once"),
        ('`${pack.label} fields added.`', '`已添加 ${pack.label} 字段。`', "once"),
        ("No blocks in the master block, so nothing is sent and nothing is drawn.</div>",
         "主信息块中没有信息块，因此不会发送任何内容，也不会绘制任何内容。</div>", "once"),
        ('"[Only appears when the story introduces a new NPC.]"',
         '"[仅在故事引入新 NPC 时出现。]"', "once"),
        ("Nothing to preview yet.</div>", "暂无预览内容。</div>", "once"),
        ("Showing the templates the AI is asked to fill in.", "展示要求 AI 填写的模板。", "once"),
        ('${existing ? "Edit" : "New"} block', '${existing ? "编辑" : "新建"}信息块', "once"),
        (">Give it a name, an emoji and the template the AI fills in.</p>",
         ">为它起一个名字、选一个表情符号，并编写 AI 填写的模板。</p>", "once"),
        (">Name</div>", ">名称</div>", "once"),
        (">Shown as the header in chat</div>", ">在聊天中显示为标题</div>", "once"),
        ('placeholder="e.g. Relationship Meter"', 'placeholder="例如：关系度计量"', "once"),
        (">Emoji</div>", ">表情符号</div>", "once"),
        ("Sits before the header", "位于标题之前", "once"),
        (">Shown as</div>", ">显示为</div>", "once"),
        (">Hidden blocks are still sent and still read by the side panel</div>",
         ">隐藏的信息块仍会发送，并仍会被侧边面板读取</div>", "once"),
        (">Template</div>", ">模板</div>", "once"),
        (">What the AI is told to write. Square brackets read as fill-me-in.</div>",
         ">要求 AI 书写的内容。方括号表示待填写。</div>", "once"),
        (">Tag: <code id=\"blk_tag_preview\">", ">标签：<code id=\"blk_tag_preview\">", "once"),
        ('"${label}" saved.', '“${label}”已保存。', "once"),
    ],
}
