#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Megumin-Suite 中文本地化 映射批 4b：故事导演 + 屏蔽列表
SD_FLAVORS 为写入值（进 Prompt），保留英文；SD_GENRES 的 label/desc 仅显示，可译。"""

MAPS = {
    # ═══════════════════════════ storyplan/ui.js ═══════════════════════════
    "src/features/storyplan/ui.js": [
        ('label: "Slice of Life", desc: "Daily rhythms, small moments, character-driven warmth."',
         'label: "日常", desc: "日常节奏、小瞬间、角色驱动的温情。"', "once"),
        ('label: "Drama", desc: "Emotional conflict, relationship tension, high stakes feelings."',
         'label: "剧情", desc: "情感冲突、关系张力、高风险的感受。"', "once"),
        ('label: "Romance", desc: "Love as the central engine — pursuit, longing, devotion."',
         'label: "恋爱", desc: "以爱为核心引擎——追求、渴望、奉献。"', "once"),
        ('label: "Action / Adventure", desc: "Physical danger, quests, combat, exploration."',
         'label: "动作 / 冒险", desc: "身体危险、任务、战斗、探索。"', "once"),
        ('label: "Mystery / Thriller", desc: "Secrets, investigation, paranoia, carefully timed reveals."',
         'label: "悬疑 / 惊悚", desc: "秘密、调查、偏执、精心安排的揭示。"', "once"),
        ('label: "Fantasy / RPG", desc: "Magic systems, world-building, quests, power progression."',
         'label: "奇幻 / RPG", desc: "魔法体系、世界观构建、任务、力量成长。"', "once"),
        ('label: "Horror / Dark", desc: "Dread, survival, psychological terror, body horror."',
         'label: "恐怖 / 黑暗", desc: "恐惧、求生、心理恐怖、身体恐怖。"', "once"),
        ('label: "Sci-Fi", desc: "Technology, space, dystopia, transhumanism."',
         'label: "科幻", desc: "科技、太空、反乌托邦、超人类主义。"', "once"),
        ('label: "Comedy", desc: "Humor-driven, absurdist, sitcom energy, comedic timing."',
         'label: "喜剧", desc: "幽默驱动、荒诞主义、情景喜剧能量、喜剧节奏。"', "once"),
        ('label: "Anime / Light Novel", desc: "Genre-savvy tropes, ensemble cast, escalating arcs, tonal swings played straight."',
         'label: "动画 / 轻小说", desc: "懂行的类型套路、群像阵容、层层升级的篇章、一本正经的基调摇摆。"', "once"),
        ('label: "Tabletop RPG", desc: "D&D, Delta Green, Call of Cthulhu — a party, a table, and a world that answers to rules."',
         'label: "桌面 RPG", desc: "D&D、Delta Green、克苏鲁的呼唤——一支队伍、一张桌子，以及一个遵守规则的世界。"', "once"),
        ('label: "Psychological", desc: "Interior pressure, unreliable perception, obsession, a slow unravelling."',
         'label: "心理", desc: "内在压力、不可靠的感知、执念、缓慢的崩解。"', "once"),
        ('label: "Free-form", desc: "No genre conventions imposed. The story goes wherever the scene takes it."',
         'label: "自由形式", desc: "不施加任何类型惯例。故事随场景走向任何地方。"', "once"),
        (">Custom…</option>", ">自定义…</option>", "once"),
        ("<h2>Story Director</h2>", "<h2>故事导演</h2>", "once"),
        ("<p>Direct the narrative. Shape what happens next.</p>", "<p>导演叙事。塑造接下来发生的事。</p>", "once"),
        ("? 'Enabled' : 'Disabled'}", "? '已启用' : '已禁用'}", "once"),
        ("<strong>V10 does not really need this.</strong> Its engine already drives the plot\n            forward on its own, so the Director is optional rather than recommended there. Switch it\n            on if you want a hand on the wheel &mdash; a specific arc, a pace change, a beat you want\n            reached &mdash; and leave it off otherwise.</span>",
         "<strong>V10 其实不太需要它。</strong>其引擎本身就会推动剧情，因此故事导演在此是可选而非推荐。若你想搭把手——某个具体篇章、节奏变化、想达成的节拍——就开启它，否则保持关闭。</span>", "once"),
        ("> Enable Story Director</div>", "> 启用故事导演</div>", "once"),
        ("Analyze your RP and generate narrative directives that steer the plot forward.",
         "分析你的角色扮演，生成引导剧情前进的叙事指令。", "once"),
        ("> Director's Console</div>", "> 导演控制台</div>", "once"),
        (">Content Rating</div>", ">内容分级</div>", "once"),
        ("> No Limit", "> 无限制", "once"),
        ("> SFW", "> SFW", "once"),
        ("> NSFW", "> NSFW", "once"),
        (">Pacing</div>", ">节奏</div>", "once"),
        (">Slow Burn</span>", ">慢热</span>", "once"),
        (">Character moments, no rush</span>", ">角色时刻，不急不缓</span>", "once"),
        (">Organic flow, balanced</span>", ">自然流动，均衡推进</span>", "once"),
        (">Accelerate</span>", ">加速</span>", "once"),
        (">Push forward, big moves</span>", ">大步向前，动作要猛</span>", "once"),
        (">Primary Genre</div>", ">主要类型</div>", "once"),
        ('placeholder="e.g. cosmic horror western, courtroom drama"',
         'placeholder="例如：宇宙恐怖西部片、法庭剧"', "once"),
        ("? 'Type the genre and the conventions that come with it. Sent to the Director exactly as written.'",
         "? '输入类型及其伴随的惯例。将按原样发送给导演。'", "all"),
        (">Flavor Tags <span class=\"sd-label-hint\">(pick up to 3)</span></div>",
         ">风味标签 <span class=\"sd-label-hint\">（最多选 3 个）</span></div>", "once"),
        ("> Unrestricted Content</div>", "> 无限制内容</div>", "once"),
        ("Inject a content policy override into the story context. Enables darker, more explicit narrative directions without AI refusals.",
         "向故事上下文注入内容策略覆盖。允许更黑暗、更露骨的叙事方向，而不触发 AI 拒绝。", "once"),
        ("> Director's Note</div>", "> 导演备注</div>", "once"),
        ("> Current Directive</div>", "> 当前指令</div>", "once"),
        ("</i> Generate Directive</button>", "</i> 生成指令</button>", "once"),
        ("</i> Evolve</button>", "</i> 进化</button>", "once"),
        ('placeholder="Your narrative directive will appear here after generation."',
         'placeholder="生成后，你的叙事指令将显示在这里。"', "once"),
        ("This directive is injected via <code>[[storyplan]]</code>. A feedback tracker is appended via <code>[[storytracker]]</code>.",
         "此指令通过 <code>[[storyplan]]</code> 注入。反馈追踪器通过 <code>[[storytracker]]</code> 追加。", "once"),
        ("> Engine Settings</div>", "> 引擎设置</div>", "once"),
        (">Generation Backend</div>", ">生成后端</div>", "once"),
        (">Context Limit</div>", ">上下文限制</div>", "once"),
        ("How much chat history the Director reads to analyze the plot.",
         "故事导演读取多少聊天历史来分析剧情。", "once"),
        (">Last 100 Messages</option>", ">最近 100 条消息</option>", "once"),
        (">Full Chat History</option>", ">完整聊天历史</option>", "once"),
        (">Auto-Trigger Mode</div>", ">自动触发模式</div>", "once"),
        ("When should the Director evolve the story?", "故事导演应在何时进化故事？", "once"),
        (">Manual Only</option>", ">仅手动</option>", "once"),
        (">Auto (Smart Status)</option>", ">自动（智能状态）</option>", "once"),
        (">Every X Replies (Safety Net)</option>", ">每 X 条回复（安全网）</option>", "once"),
        ('title="Fallback safety net interval"', 'title="回退安全网间隔"', "once"),
        ('title: "Advanced: Edit Prompts"', 'title: "高级：编辑提示词"', "once"),
        ('label: "System Prompt (Manifesto)"', 'label: "系统提示词（宣言）"', "once"),
        ('label: "User Task Prompt"', 'label: "用户任务提示词"', "once"),
        ('label: "Thinking Instructions"', 'label: "思考指令"', "once"),
        ('label: "Directive Injection Template"', 'label: "指令注入模板"', "once"),
        ('label: "Story Tracker Template"', 'label: "故事追踪器模板"', "once"),
        ('"Maximum 3 flavor tags allowed."', '"最多允许 3 个风味标签。"', "once"),
        ('"Not enough chat history to generate a directive."', '"聊天历史不足，无法生成指令。"', "once"),
        ("? 'Evolving...' : 'Directing...'}", "? '进化中...' : '导演中...'}", "once"),
        ('"Chat changed while the directive was generating. It was discarded."',
         '"指令生成过程中聊天发生了变化，已丢弃。"', "once"),
        ('isEvolve ? "Directive Evolved!" : "Directive Generated!"',
         'isEvolve ? "指令已进化！" : "指令已生成！"', "once"),
        ('"AI failed to format the directive correctly. Try again."',
         '"AI 未能正确格式化指令。请重试。"', "once"),
        ('"Failed to generate directive."', '"生成指令失败。"', "once"),
    ],
    # ═══════════════════════════ banlist/ui.js ═══════════════════════════
    "src/features/banlist/ui.js": [
        ("> AI Slop Detector</div>", "> AI 劣质词检测器</div>", "once"),
        ("> Analyze Chat</button>", "> 分析聊天</button>", "once"),
        (">Generator Backend</div>", ">生成后端</div>", "once"),
        (">Choose how to generate the analysis.</div>", ">选择如何生成分析。</div>", "once"),
        (">Direct API Call (Fast)</option>", ">直接 API 调用（快速）</option>", "once"),
        (">Megumin Engine Preset</option>", ">Megumin 引擎预设</option>", "once"),
        ("</i> Add Phrase</div>", "</i> 添加短语</div>", "once"),
        ('placeholder="Manually add a phrase to ban…"', 'placeholder="手动添加要屏蔽的短语…"', "once"),
        (">Add</button>", ">添加</button>", "once"),
        ("</i> Active Banned Phrases</div>", "</i> 已启用的屏蔽短语</div>", "once"),
        ("</i> Import</button>", "</i> 导入</button>", "once"),
        ("</i> Export</button>", "</i> 导出</button>", "once"),
        ("</i> Clear All</button>", "</i> 全部清空</button>", "once"),
        (">This is a beta feature. Don't complain if you have to generate more than once.</span>",
         ">这是测试版功能。如果需要生成多次，别抱怨。</span>", "once"),
        ('title: "Advanced: Edit Prompts"', 'title: "高级：编辑提示词"', "once"),
        ('label: "System Prompt"', 'label: "系统提示词"', "once"),
        ('label: "User Task Prompt"', 'label: "用户任务提示词"', "once"),
        ('label: "Thinking Instructions"', 'label: "思考指令"', "once"),
        ('label: "Ban List Injection Template"', 'label: "屏蔽列表注入模板"', "once"),
        (">No phrases banned yet.</span>", ">尚无已屏蔽的短语。</span>", "once"),
        ("> 0 Banned`", "> 已屏蔽 0 条`", "once"),
        ("} Banned`", "} 条已屏蔽`", "once"),
        ('"Are you sure you want to delete all banned phrases?"',
         '"确定要删除所有已屏蔽的短语吗？"', "once"),
        ('"Ban list cleared."', '"屏蔽列表已清空。"', "once"),
        ('"Ban list is empty!"', '"屏蔽列表为空！"', "once"),
        ('`Imported ${added} phrases!`', '`已导入 ${added} 条短语！`', "once"),
        ('"No new phrases imported."', '"没有导入新短语。"', "once"),
        ('"Invalid JSON format. Expected an array of strings."',
         '"JSON 格式无效。应为字符串数组。"', "once"),
        ('"Error parsing JSON file."', '"解析 JSON 文件出错。"', "once"),
        ('"Not enough chat history to analyze!"', '"聊天历史不足，无法分析！"', "once"),
        ("</i> Analyzing...`", "</i> 分析中...`", "once"),
        ('`Caught and banned ${addedCount} repetitive phrases!`',
         '`已捕获并屏蔽 ${addedCount} 条重复短语！`', "once"),
        ('"No new repetitive phrases found."', '"没有发现新的重复短语。"', "once"),
        ("</i> Analyze Chat History", "</i> 分析聊天历史", "once"),
    ],
}
