#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Megumin-Suite 中文本地化 映射批 1：核心面板 + 导航/顶栏/入口 UI
结构：{相对路径: [(old, new, mode), ...]}，mode "once"=必须恰好1次，"all"=全部替换
只翻译 100% 确认的 UI 显示字符串；identifier/逻辑键/prompt 一律不动。"""

MAPS = {
    "src/ui/tabs/coreAndCot.js": [
        ("<h2>PRESETS & COT</h2>", "<h2>预设与思维链</h2>", "once"),
        ("<p>Choose the core preset, and COT.</p>", "<p>选择核心预设与思维链。</p>", "once"),
        (">Configuration</div>", ">配置</div>", "once"),
        ("> Official Engines</span>", "> 官方引擎</span>", "once"),
        ("> Custom Engines</span>", "> 自定义引擎</span>", "once"),
        ("> Story Config</span>", "> 故事设置</span>", "once"),
        ('<span class="ws-new-pill">✨ New</span>', '<span class="ws-new-pill">✨ 新</span>', "once"),
        ("> Reasoning (CoT)</span>", "> 推理（CoT）</span>", "once"),
        ("'ON' : 'OFF'", "'开' : '关'", "once"),
        ("> Official Megumin Engines</h3>", "> Megumin 官方引擎</h3>", "once"),
        ('<strong>Pro Tip:</strong> The Engine defines the "laws of physics" and pacing of your story. The Reasoning acts as the AI\'s internal scratchpad. For the best experience, match V9 Mirage with CoT V9 Mirage.',
         '<strong>使用提示：</strong>引擎定义了故事的“物理法则”与节奏。推理则是 AI 的内部草稿纸。为获得最佳体验，请将 V9 Mirage 引擎与 CoT V9 Mirage 搭配使用。', "once"),
        (">All <span class=\"pill-count\">", ">全部 <span class=\"pill-count\">", "once"),
        ("<h3>V6 Engines are in the forge.</h3><p>Stay tuned for the next update! Later this week.</p>",
         "<h3>V6 引擎正在锻造中。</h3><p>敬请期待下次更新！本周晚些时候。</p>", "once"),
        ("> Recommended</span>", "> 推荐</span>", "once"),
        ('ecard-badge new">New</span>', 'ecard-badge new">新</span>', "all"),
        ("> Coming Soon</span>", "> 即将推出</span>", "once"),
        ("</i> Active</span>", "</i> 使用中</span>", "all"),
        ("</i> Enhanced Dialogue</span>", "</i> 增强对话</span>", "once"),
        ("The original Secret Sauce. NPCs react naturally — no simping, no needless hostility.",
         "最初的秘制配方。NPC 反应自然——不献媚，也无无谓敌视。", "once"),
        ("New and improved balance mode that aims to use less tokens and more creativity.",
         "全新改进的平衡模式，旨在使用更少 token、带来更多创意。", "once"),
        ("Hollywood-inspired storytelling. Dramatic beats and heightened tension.",
         "好莱坞式叙事。戏剧性节拍与张力拉满。", "once"),
        ("Balance but harsher. The world is unforgiving and consequences hit harder.",
         "平衡模式的更严酷版本。世界毫不留情，后果更加沉重。", "once"),
        ("Advanced cinematic framing and pacing. Designed to emulate high-budget anime direction.",
         "高级电影化构图与节奏。旨在复刻高预算动画的导演水准。", "once"),
        ("The ultimate 6-specialist writer room. Unprecedented narrative consistency and realism.",
         "终极 6 专家写作团队。前所未有的叙事一致性与真实感。", "once"),
        ("A streamlined version of the Dream Team. Faster generation with lower token overhead.",
         "梦之队的精简版。更快的生成与更低的 token 开销。", "once"),
        ("The V7 Core engine. The perfect middle ground: cinematic pacing, realistic friction, and relentless world progression.",
         "V7 Core 引擎。完美的中间地带：电影化节奏、真实的摩擦感与不停歇的世界推进。", "once"),
        ("The V7 Reality engine. Grounded, unrelenting simulation with zero narrative protection.",
         "V7 Reality 引擎。脚踏实地、毫不留情的模拟，零叙事保护。", "once"),
        ("The V7 Gentle engine. A softer, more intimate storytelling flow.",
         "V7 Gentle 引擎。更柔和、更私密的叙事流。", "once"),
        ("The Kismet engine. Focused purely on inescapable narrative momentum, pushing the story forward as the unseen author of fate.",
         "Kismet 引擎。纯粹聚焦于不可逃脱的叙事动量，如同命运的无形作者推动故事前进。", "once"),
        ("Unmatched in complex human psychology, authentic flawed dialogue, and autonomous, multi-layered story plotting.",
         "在复杂人类心理、真实有缺陷的对话，以及自主多层次剧情构建方面无与伦比。", "once"),
        ("A streamlined, highly efficient version of Obsidian. Retains the core rules of psychology, dialogue, and momentum with a much lighter token footprint.",
         "Obsidian 的高效精简版。以轻得多的 token 占用保留心理、对话与动量的核心规则。", "once"),
        ("The absolute pinnacle of the Megumin Suite. A hybrid engine mixing V8 Obsidian's deep psychology with V6 Dream Team's specialist writer room framework.",
         "Megumin Suite 的绝对巅峰。融合 V8 Obsidian 深层心理与 V6 梦之队专家写作团队框架的混合引擎。", "once"),
        ("The storyteller. Ukiyo is the looser of the two — a teller with a temperament, spinning the world and its history, following whatever in the scene is most alive. It trades a little polish for invention: the prose wanders, reaches for an image, and occasionally overreaches. Pick it for atmosphere, momentum and a world that feels told rather than composed. Neither V10 is a downgrade of the other — run a few scenes on each and keep the one that sounds like the story you want to read.",
         "讲述者。Ukiyo 是二者中更自由的一个——一位有脾气的说书人，编织世界与历史，追随场景中最鲜活的东西。它以少许打磨换取创意：文字自由游走、捕捉意象，偶尔用力过猛。为氛围、动量与一个“被讲述出来”而非“被编排出来”的世界而选它。两款 V10 并非彼此的降级——各自试几场，留下听起来像你想读的故事的那一款。", "once"),
        ("The writer. Shura is the stricter of the two — no slop, no AI tells, no line that exists to manage the scene. Every character is the protagonist of their own story, acting from their own values, and none of them is a villain in their own eyes; there is no objective right or wrong for the narration to take sides on. Pick it for prose that reads like a book and a cast that drives the story itself. Neither V10 is a downgrade of the other — run a few scenes on each and keep the one that sounds like the story you want to read.",
         "写作者。Shura 是二者中更严格的一个——没有劣质文字、没有 AI 腔、没有为了管理场景而存在的句子。每个角色都是自己故事的主角，依自身价值观行动，没有人自认是反派；叙事无需站队的绝对对错。为读起来像书一般的文字、由群像自身驱动的故事而选它。两款 V10 并非彼此的降级——各自试几场，留下听起来像你想读的故事的那一款。", "once"),
        ("Ukiyo, with the narrator writing {{user}} as well. It reads how you write — diction, rhythm, how boldly you act — and plays your character in that voice. Anything you write yourself is canon and is never overwritten or corrected. Your history stays yours; only the acting is shared.",
         "Ukiyo，同时由叙述者代写 {{user}}。它会读懂你的写作方式——措辞、节奏、你行动的大胆程度——并以那个声音扮演你的角色。你自己写的内容即为正典，永不被覆盖或修正。你的过往依然属于你；共享的只有演绎。", "once"),
        ("Shura with shared authorship: every character is a protagonist, {{user}} among them, and the narrator writes them all in your voice. It yields the moment you take a turn back, and never invents your past. For hands-off, cinematic play — watching the story rather than steering each beat.",
         "Shura 的共著版本：每个角色都是主角，{{user}} 也在其中，叙述者以你的声音书写他们全部。当你收回回合时它会即刻让位，且从不虚构你的过去。适合放手式电影化游玩——观看故事，而非操控每个节拍。", "once"),
        ("The definitive, final Megumin V9 Preset. V9 Mirage is the absolute pinnacle of narrative simulation, delivering hyper-realistic psychology, visceral atmospheric grounding, and dynamic world consequences. This is the ultimate, highly recommended preset.",
         "权威的、最终的 Megumin V9 预设。V9 Mirage 是叙事模拟的绝对巅峰，带来超真实心理、切肤的环境质感与动态的世界后果。这是终极且强烈推荐的预设。", "once"),
        ("An experimental beta engine with a slightly different, highly stylized narrative flow. Proved interesting enough to include for those who want an alternative storytelling rhythm. Note: this doesn't support custom Writing style it have it own one. ",
         "实验性 beta 引擎，拥有略有不同、高度风格化的叙事流。事实证明它足够有趣，值得收录给想要另一种叙事节奏的人。注意：它不支持自定义写作风格，因为它有自己的一套。", "once"),
        ("A unique beta hybrid blending the specialized writer-room mechanics of V8 Fusion with the raw psychological depth of V9 Xin. Highly experimental. Note: this doesn't support custom Writing style it have it own one.",
         "独特的 beta 混合引擎，融合 V8 Fusion 的专业写作团队机制与 V9 Xin 的原始心理深度。高度实验性。注意：它不支持自定义写作风格，因为它有自己的一套。", "once"),
        ("A streamlined, lightweight version of V9 Mirage. It retains the core philosophy and brutal realism of Mirage but runs with a smaller context footprint. V9 Mirage is still recommended if your model can handle it.",
         "V9 Mirage 的精简轻量版。保留 Mirage 的核心理念与残酷现实主义，但以更小的上下文占用运行。如果你的模型能承受，仍推荐 V9 Mirage。", "once"),
        ("> V7 Modules (Turn off to disable)</div>", "> V7 模块（关闭以禁用）</div>", "once"),
        ('label: "OOC Protocol", desc: "Allows out-of-character directives."',
         'label: "OOC 协议", desc: "允许角色外指令。"', "once"),
        ('label: "PC Solo Physicality", desc: "Narration of PC when unobserved."',
         'label: "PC 独处描写", desc: "未被观察时对 PC 的旁白。"', "once"),
        ('label: "Introduction Protocol", desc: "How new NPCs enter the story."',
         'label: "登场协议", desc: "新 NPC 如何进入故事。"', "once"),
        ('label: "Cultural Anchoring", desc: "Real-world integration and references."',
         'label: "文化锚定", desc: "现实世界的整合与引用。"', "once"),
        ('label: "Scene Choreography", desc: "Focus shifting and crowd management."',
         'label: "场景调度", desc: "焦点切换与人群管理。"', "once"),
        ("> Your Custom Engines</h3>", "> 你的自定义引擎</h3>", "once"),
        ("No custom engines yet. Go to Dev Mode to create or import one!",
         "还没有自定义引擎。前往开发模式创建或导入一个吧！", "once"),
        ("</i> Edit", "</i> 编辑", "once"),
        ("Custom Engine Flow", "自定义引擎流程", "once"),
        ("> Chain of Thought (Reasoning)</h3>", "> 思维链（推理）</h3>", "once"),
        ("Enable Chain of Thought</div>", "启用思维链</div>", "once"),
        ("Toggle the entire AI reasoning system. When off, the AI generates responses directly.",
         "切换整个 AI 推理系统。关闭时 AI 直接生成回复。", "once"),
        ("<strong>Custom Engine Logic Active</strong> — This Engine provides its own [[COT]] and [[prefill]]. Selections below will be overridden by the Engine's code.",
         "<strong>自定义引擎逻辑已激活</strong>——该引擎自带 [[COT]] 与 [[prefill]]。以下选择将被引擎代码覆盖。", "once"),
        ("> Select Framework</div>", "> 选择框架</div>", "once"),
        ('label: "CoT V10 Ukiyo \\u2014 Thinking Cap"', 'label: "CoT V10 Ukiyo — 思考上限"', "once"),
        ('label: "CoT V10 Shura \\u2014 Thinking Cap"', 'label: "CoT V10 Shura — 思考上限"', "once"),
        ('label: "CoT V1 (Classic)"', 'label: "CoT V1（经典）"', "once"),
        ('label: "CoT V2 (New)"', 'label: "CoT V2（新版）"', "once"),
        ('label: "CoT V6 (Dream Team)"', 'label: "CoT V6（梦之队）"', "once"),
        ('label: "CoT V6 (Lite)"', 'label: "CoT V6（精简版）"', "once"),
        ('label: "CoT V7 (Lite)"', 'label: "CoT V7（精简版）"', "once"),
        ('label: "CoT V9 Cui (Lite)"', 'label: "CoT V9 Cui（精简版）"', "once"),
        ("The long-form reasoning built for Ukiyo. Thinks like a novelist muttering before a draft \\u2014 present tense, a little messy, never a plan. No phases, no checklists, no audits.",
         "为 Ukiyo 打造的长篇推理。像小说家在动笔前喃喃自语——现在时、略显凌乱、从不制定计划。没有阶段、没有清单、没有检查。", "once"),
        ("The same writer's mind with a hard ceiling on the thinking phase. For models that over-think.",
         "同一个作者的心智，但为思考阶段设了硬性上限。适合想太多的模型。", "once"),
        ("Seven rules carried into the writing rather than a plan made before it. Built for V10 Shura, and the lightest of the four.",
         "七条规则直接带进写作，而非动笔前先做计划。为 V10 Shura 打造，四个中最轻量。", "once"),
        ("The same seven rules with a hard ceiling on the thinking phase. For models that over-think.",
         "同样的七条规则，但为思考阶段设了硬性上限。适合想太多的模型。", "once"),
        ("The original 8-step framework. Focuses heavily on the NPC's internal emotional landscape vs their observable actions.",
         "最初的 8 步框架。高度聚焦 NPC 的内部情感图景与其可观察行为之间的对比。", "once"),
        ("The new experimental framework. Stricter reality checks, info audits, better NPCs, and hook generation.",
         "新的实验性框架。更严格的事实核查、信息审计、更好的 NPC，以及钩子生成。", "once"),
        ("The full 4-phase sequence designed specifically for V6 engines. Specialized validation and modeling.",
         "专为 V6 引擎设计的完整 4 阶段流程。专业化的验证与建模。", "once"),
        ("A streamlined 3-phase sequence. Less token overhead while maintaining narrative rules.",
         "精简的 3 阶段流程。在保持叙事规则的同时降低 token 开销。", "once"),
        ("The new V7 sequence with 5-phase strict ground truth rebuilding.",
         "全新的 V7 流程，采用 5 阶段严格事实重建。", "once"),
        ("A streamlined 5-phase sequence for V7.", "为 V7 精简的 5 阶段流程。", "once"),
        ("The new V7.5 sequence focused on story engine mechanics.",
         "全新的 V7.5 流程，聚焦故事引擎机制。", "once"),
        ("The new V8 narrative processing sequence.", "全新的 V8 叙事处理流程。", "once"),
        ("The new V8 Fusion narrative processing sequence.", "全新的 V8 Fusion 叙事处理流程。", "once"),
        ("The primary and most balanced reasoning sequence, purpose-built for the V9 Mirage engine. The gold standard for modern roleplay.",
         "最主流且最均衡的推理流程，专为 V9 Mirage 引擎打造。现代角色扮演的金标准。", "once"),
        ("A lighter, version of CoT V9 Mirage, it give Different output Try and see if you like.",
         "CoT V9 Mirage 的轻量版本，会给出不同的输出，试试看喜不喜欢。", "once"),
        ("The heavy-duty, maximum-thinking sequence. Forces the AI to dive incredibly deep into sensory data and psychological realism before generating a single word.",
         "重负载、最大化思考的流程。迫使 AI 在生成第一个字之前，深入感官数据与心理真实感。", "once"),
        ("A specialized multi-agent reasoning sequence designed specifically to pair with the V9 Kuromaku engine.",
         "专门设计用于搭配 V9 Kuromaku 引擎的多智能体推理流程。", "once"),
        ("A highly streamlined, fast-executing reasoning sequence perfectly paired with the V9 Cui engine to save tokens.",
         "高度精简、快速执行的推理流程，与 V9 Cui 引擎完美搭配以节省 token。", "once"),
        ("> May be Incompatible</span>", "> 可能不兼容</span>", "once"),
        ("> Thinking Effort</div>", "> 思考强度</div>", "once"),
        ('label: "100 Words"', 'label: "100 词"', "once"),
        ('label: "250 Words"', 'label: "250 词"', "once"),
        ('label: "450 Words"', 'label: "450 词"', "once"),
        ('label: "Custom" }', 'label: "自定义" }', "once"),
        ('label: "Unspecified" }', 'label: "未指定" }', "once"),
        ("Custom Word Count", "自定义词数", "once"),
        ("Gemini Thinking Override", "Gemini 思考覆盖", "once"),
        ("Enable ONLY for Gemini models to inject specific XML tags.",
         "仅对 Gemini 模型启用，用于注入特定 XML 标签。", "once"),
        ("> Reasoning Language</div>", "> 推理语言</div>", "once"),
        ('label: "English" }', 'label: "英语" }', "all"),
        ('label: "Arabic (العربية)"', 'label: "阿拉伯语（العربية）"', "once"),
        ('label: "Spanish (Español)"', 'label: "西班牙语（Español）"', "once"),
        ('label: "French (Français)"', 'label: "法语（Français）"', "once"),
        ('label: "Mandarin (中文)"', 'label: "中文（简体）"', "once"),
        ('label: "Russian (Русский)"', 'label: "俄语（Русский）"', "once"),
        ('label: "Japanese (日本語)"', 'label: "日语（日本語）"', "once"),
        ('label: "Portuguese (Português)"', 'label: "葡萄牙语（Português）"', "once"),
        ("> Pro Tip</span>", "> 使用提示</span>", "once"),
    ],
    "src/ui/tabs.js": [
        ('<i class="fa-solid fa-code"></i> Dev', '<i class="fa-solid fa-code"></i> 开发', "once"),
        ("is stored globally already — it is the same on every character.",
         "已全局存储——每个角色上都是一样的。", "once"),
        ("This tab has nothing to sync.", "此标签页没有可同步的内容。", "all"),
        ("The panel is still showing the previous chat's settings. Reopen it and try again.",
         "面板仍显示上一个聊天的设置。请重新打开面板再试一次。", "once"),
        ("now applies to every character. Changes here follow automatically.",
         "现在应用于所有角色。此处的更改会自动同步。", "once"),
        ("is back to per-character.", "已恢复为按角色独立。", "once"),
        ("</i> Global`", "</i> 全局`", "once"),
        ("This tab is stored globally already.", "此标签页已全局存储。", "once"),
        ('Global: ${on ? "On" : "Off"}', 'Global: ${on ? "开启" : "关闭"}', "once"),
        ("Every change on the ${title} tab is copied to all characters. Click to stop.",
         "${title} 标签页上的每个更改都会复制到所有角色。点击停止。", "once"),
        ("Changes on the ${title} tab stay with this character. Click to make them global.",
         "${title} 标签页上的更改只保留在此角色。点击使其全局生效。", "once"),
    ],
    "example.html": [
        ("When on, every change on this tab is applied to all characters and groups.",
         "开启时，此标签页上的每个更改都会应用到所有角色与群组。", "once"),
        ("> Global: Off</button>", "> 全局：关闭</button>", "once"),
        ("> Reset</button>", "> 重置</button>", "once"),
        ("> Dev</button>", "> 开发</button>", "once"),
        ("> Saved</div>", "> 已保存</div>", "once"),
        ("> Save & Close</button>", "> 保存并关闭</button>", "once"),
        (">Global Default</div>", ">全局默认</div>", "once"),
        (">Tavern Profile</h2>", ">酒馆档案</h2>", "once"),
    ],
    "index.js": [
        ("You have unsaved changes in your custom engine. Are you sure you want to exit? Changes will be lost.",
         "你的自定义引擎有未保存的更改。确定要退出吗？更改将丢失。", "once"),
        ("You have unsaved changes in your custom engine. Are you sure you want to close? Changes will be lost.",
         "你的自定义引擎有未保存的更改。确定要关闭吗？更改将丢失。", "once"),
        ('title="Menu"', 'title="菜单"', "once"),
        (">Navigation</h3>", ">导航</h3>", "once"),
        ('? "On" : "Off"}', '? "开启" : "关闭"}', "once"),
        ("</i> Reset Profile", "</i> 重置档案", "once"),
        ("Are you sure you want to completely reset this character's profile to the default template?",
         "确定要将此角色的档案完全重置为默认模板吗？", "once"),
        ("Profile has been reset to defaults.", "档案已重置为默认值。", "once"),
        ("Workflow Configured & Applied Successfully!", "工作流配置并应用成功！", "once"),
        ("Auto-Evolving Narrative Directive...", "正在自动进化叙事指令...", "once"),
        ('"Story Director"', '"故事导演"', "all"),
        ("Narrative Directive Evolved silently!", "叙事指令已静默进化！", "once"),
        ("Background Memory Scan Triggered...", "已触发后台记忆扫描...", "once"),
        ("NPC added to Bank: ${npcName}", "NPC 已加入图鉴：${npcName}", "once"),
        ('`Megumin Suite — ${who} updated`', '`Megumin Suite — ${who} 已更新`', "once"),
        ('"added" : e.op === "-" ? "removed" : "replaced"', '"已添加" : e.op === "-" ? "已移除" : "已替换"', "once"),
        ("[Generating Image...]", "[正在生成图像...]", "once"),
        ("Image tag ${idx + 1} detected. Sending to ComfyUI...",
         "检测到第 ${idx + 1} 个图像标签，正在发送到 ComfyUI...", "once"),
        ("Regenerating Image...", "正在重新生成图像...", "once"),
        ('title="Visualize Last Scene (Manual)"', 'title="可视化上一场景（手动）"', "once"),
    ],
}
