#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Megumin-Suite 中文本地化 映射批 3：侧边面板"""

MAPS = {
    # ═══════════════════════════ sidepanel/panel.js ═══════════════════════════
    "src/sidepanel/panel.js": [
        ('title: "Megumin Suite Trackers"', 'title: "Megumin Suite 追踪器"', "once"),
        ('" Megumin Trackers"', '" Megumin 追踪器"', "once"),
        ('title: "Open NPC Book"', 'title: "打开 NPC 图鉴"', "once"),
        ('title: "Refresh from latest message"', 'title: "从最新消息刷新"', "once"),
        ('title: "Collapse panel"', 'title: "折叠面板"', "once"),
        ('"No tracker data yet. The panel updates whenever the AI emits a World State or NPC Inner Chatter block."',
         '"暂无追踪数据。每当 AI 输出世界状态或 NPC 内心独白信息块时，面板就会更新。"', "all"),
        ('"Open Megumin Suite (wand icon) at least once first."',
         '"请先至少打开一次 Megumin Suite（魔杖图标）。"', "once"),
        ('"NPC Book"', '"NPC 图鉴"', "once"),
        ('title: "Alt+↑/↓ to reorder"', 'title: "Alt+↑/↓ 重新排序"', "once"),
        ('"All sections are hidden. Re-enable them in the Side Panel settings tab."',
         '"所有区块均已隐藏。请在侧边面板设置页中重新启用。"', "once"),
        ('name: "World State"', 'name: "世界状态"', "once"),
        ('name: "NPC Inner Chatter"', 'name: "NPC 内心独白"', "once"),
        ('name: "New NPC"', 'name: "新 NPC"', "once"),
        ('${names.length === 1 ? "A block was" : "Blocks were"} found in the last reply but could not be read: ${names.join(", ")}.',
         '最后一条回复中发现${names.length === 1 ? "一个" : "多个"}信息块，但无法读取：${names.join(", ")}。', "once"),
    ],
    # ═══════════════════════════ sidepanel/sections.js ═══════════════════════════
    "src/sidepanel/sections.js": [
        ('kv("Date & Time", ', 'kv("日期与时间", ', "once"),
        ('kv("Location", ', 'kv("地点", ', "once"),
        ('kv("Weather", ', 'kv("天气", ', "once"),
        ('kv("Arc Phase", ', 'kv("弧线阶段", ', "once"),
        ('kv("Scene Phase", ', 'kv("场景阶段", ', "once"),
        ('" Off-Screen"', '" 画面之外"', "once"),
        ('" Unresolved Threads"', '" 未解决的线索"', "once"),
        ('" Planted Seeds"', '" 埋下的种子"', "once"),
        ('" Consequence Timers"', '" 后果倒计时"', "once"),
        ('n.name || "Unnamed NPC"', 'n.name || "未命名 NPC"', "once"),
        ('"(no parsed fields)"', '"（无解析字段）"', "once"),
        ('"Story Planner is empty."', '"故事规划器为空。"', "once"),
        ('title: "Open the full NPC Book (browse, edit, upload, generate portraits)"',
         'title: "打开完整 NPC 图鉴（浏览、编辑、上传、生成头像）"', "once"),
        ('" Open NPC Book"', '" 打开 NPC 图鉴"', "once"),
        ('"No NPCs banked yet. They get added automatically as the AI introduces them."',
         '"尚无 NPC 入库。AI 引入重要 NPC 时会自动添加。"', "once"),
        ('title: "Click to open in NPC Book"', 'title: "点击在 NPC 图鉴中打开"', "once"),
        ('n.name || "Unnamed"', 'n.name || "未命名"', "once"),
        ('title: "World State"', 'title: "世界状态"', "once"),
        ('title: "NPC Inner Chatter"', 'title: "NPC 内心独白"', "once"),
        ('title: "New NPC Dossiers"', 'title: "新 NPC 档案"', "once"),
        ('title: "Story Planner"', 'title: "故事规划器"', "once"),
        ('title: "NPC Bank"', 'title: "NPC 图鉴"', "once"),
        ('title: "Ban List"', 'title: "屏蔽列表"', "once"),
    ],
    # ═══════════════════════════ sidepanel/presentBar.js ═══════════════════════════
    "src/sidepanel/presentBar.js": [
        ('title="Collapse / expand"', 'title="折叠 / 展开"', "once"),
        ('<span class="meg-pb-toggle-label">Characters</span>',
         '<span class="meg-pb-toggle-label">角色</span>', "once"),
        ("> Present Characters", "> 在场角色", "once"),
        ('<div class="meg-pb-empty">No characters in scene</div>',
         '<div class="meg-pb-empty">场景中没有角色</div>', "once"),
        ('sheetSection("This Scene", ', 'sheetSection("本场景", ', "once"),
        ('sheetSection("Dossier", ', 'sheetSection("档案", ', "once"),
        ('fieldRow("Role", ', 'fieldRow("身份", ', "once"),
        ('fieldRow("Orientation", ', 'fieldRow("取向", ', "once"),
        ('fieldRow("Where to Find", ', 'fieldRow("在哪里找到", ', "once"),
        ('fieldRow("Appearance", ', 'fieldRow("外貌", ', "once"),
        ('fieldRow("Voice", ', 'fieldRow("嗓音", ', "once"),
        ('fieldRow("Personality", ', 'fieldRow("性格", ', "once"),
        ('fieldRow("Inner Circle", ', 'fieldRow("核心圈子", ', "once"),
        ('fieldRow("Background", ', 'fieldRow("背景", ', "once"),
        ('fieldRow("Read on PC", ', 'fieldRow("可在 PC 上读取", ', "once"),
        ('fieldRow("Agenda (long-term)", ', 'fieldRow("议程（长期）", ', "once"),
        ('fieldRow("Secrets", ', 'fieldRow("秘密", ', "once"),
        ('fieldRow("Canon Lock", ', 'fieldRow("正典锁定", ', "once"),
        ("> Open in NPC Book", "> 在 NPC 图鉴中打开", "once"),
        ('Not in NPC Bank yet — banks fill automatically when the AI emits a "🆕 New NPC" dossier.',
         '尚未收入 NPC 图鉴——当 AI 输出“🆕 新 NPC”档案时，图鉴会自动填充。', "once"),
        ('aria-label="Close"', 'aria-label="关闭"', "once"),
        ('title="Close (Esc)"', 'title="关闭（Esc）"', "once"),
        ("No scene-specific info parsed for this character in the last reply.",
         "最后一条回复中没有解析到该角色的场景专属信息。", "once"),
    ],
    # ═══════════════════════════ sidepanel/chrome.js / dom.js ═══════════════════════════
    "src/sidepanel/chrome.js": [
        ('modeBtn.title = floating ? "Dock panel" : "Float panel"',
         'modeBtn.title = floating ? "停靠面板" : "浮动面板"', "once"),
    ],
}
