#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Megumin-Suite 中文本地化 映射批 2：各标签页渲染器 + 侧边面板设置 + Dev 模式"""

MAPS = {
    # ═══════════════════════════ globalAndBlocks.js ═══════════════════════════
    "src/ui/tabs/globalAndBlocks.js": [
        ('title="You edited this in Dev Mode. It no longer uses the built-in text."',
         'title="你在开发模式中编辑过此内容。它不再使用内置文本。"', "once"),
        ("</i> Custom</span>", "</i> 自定义</span>", "once"),
        ('"death": "Enables permanent consequences. Characters — including yours — can die for real. No safety net, no plot armor."',
         '"death": "启用永久性后果。角色——包括你——真的会死亡。没有安全网，没有主角光环。"', "once"),
        ('"combat": "Activates a grounded, tactical combat layer. Actions have real weight, positioning matters, and you can lose badly."',
         '"combat": "激活脚踏实地、战术性的战斗层。行动有真实分量，站位很重要，你可能会输得很惨。"', "once"),
        ('"direct": "Forces AI to say words like D and P. No dancing around the subject, no polite deflection. you know what i mean. <b>Not needed on V10</b> — that engine already writes this way, so switching it on just repeats the instruction."',
         '"direct": "迫使 AI 直说 D 和 P 这类词。不绕弯子，不礼貌回避。你懂的。<b>V10 上不需要</b>——该引擎本来就这么写，开启它只会重复指令。"', "once"),
        ('"color": "Each character\'s dialogue is color-coded for easy visual parsing."',
         '"color": "每个角色的对话都有颜色标识，便于视觉解析。"', "once"),
        ('"npc_events": "Requires all new story events to grow naturally from prior context or environmental cues — no random drama out of nowhere. V6 only."',
         '"npc_events": "要求所有新故事事件都从先前上下文或环境线索中自然生长——不凭空制造随机剧情。仅 V6。"', "once"),
        ('"dn": "Forces dialogue and narration to be wrapped in their respective XML tags. Useful for specific Models for better narration style adherence. <b>Not recommended on V10</b> — the tags fight that engine\'s own prose rules."',
         '"dn": "强制对话与旁白分别包裹在各自的 XML 标签中。对特定模型更好地遵循旁白风格有用。<b>V10 上不推荐</b>——标签会与该引擎自身的行文规则冲突。"', "once"),
        ('"html": "When a character reads something — a phone screen, a letter, a sign — the AI draws the thing itself as HTML instead of describing it. Rare by design: one per reply at most, and most replies have none."',
         '"html": "当角色阅读某样东西——手机屏幕、信件、招牌——AI 直接用 HTML 画出它，而非描述。刻意少见：每条回复至多一个，多数回复没有。"', "once"),
        ('"dice_all": "Same d20 system, but everyone rolls — NPCs included. Any character who tries something that can fail gets a roll, all of them listed before the reply. Use this OR Dice, not both."',
         '"dice_all": "同一套 d20 系统，但所有人掷骰——NPC 也不例外。任何尝试可能失败之事的角色都会掷骰，且全部列在回复之前。使用此功能或 Dice，不要两者并用。"', "once"),
        ('"dice": "A d20 decides whether risky attempts land. The AI rolls before it writes the scene, so the story follows the die rather than the die following the story. The roll gets its own tab on the block card."',
         '"dice": "由 d20 决定冒险尝试是否成功。AI 在写场景前先掷骰，因此故事跟随骰子，而非骰子跟随故事。掷骰结果在信息块卡片上有独立标签页。"', "once"),
        ('"mvu": "Add MVU Compatibility still in test read more here: <a href=\'https://github.com/KritBlade/MVU_Game_Maker\' target=\'_blank\' style=\'color: var(--gold); text-decoration: underline;\'>https://github.com/KritBlade/MVU_Game_Maker</a>"',
         '"mvu": "添加 MVU 兼容性（仍在测试中），了解更多请访问：<a href=\'https://github.com/KritBlade/MVU_Game_Maker\' target=\'_blank\' style=\'color: var(--gold); text-decoration: underline;\'>https://github.com/KritBlade/MVU_Game_Maker</a>"', "once"),
        ("<h2>Global Toggles & Blocks</h2>", "<h2>全局开关与信息块</h2>", "once"),
        ("<p>Configure global parameters, gameplay add-ons, and UI tracker blocks.</p>",
         "<p>配置全局参数、玩法附加组件与 UI 追踪信息块。</p>", "once"),
        ("} Active Modules", "} 个已启用模块", "once"),
        ("<span><strong>Did you know?</strong> Global Preferences set the language and pronouns every engine reads. Gameplay Add-ons bolt extra systems onto the story — dice, death, combat, HTML props. Output Formats is just MVU, a compatibility contract with another extension. The tracker blocks live in the <b>BLOCKS</b> tab, not here.</span>",
         "<span><strong>你知道吗？</strong>全局偏好设置每个引擎都会读取的语言与代词。玩法附加组件把额外系统挂到故事上——骰子、死亡、战斗、HTML 道具。输出格式只是 MVU，即与另一个扩展的兼容契约。追踪信息块位于 <b>信息块</b> 标签页，而不是这里。</span>", "once"),
        ("> Global Preferences</div>", "> 全局偏好</div>", "once"),
        ("> V9 Dynamic Render Limits</div>", "> V9 动态渲染限制</div>", "once"),
        ("V9 switches between Lean (quick interactions) and Full (deep scenes). Set the word count ranges for each.",
         "V9 在精简（快速互动）与完整（深度场景）之间切换。为两者分别设置词数范围。", "once"),
        (">LEAN RENDER</div>", ">精简渲染</div>", "once"),
        ("Triggered by the AI for fast dialogue, back-and-forth arguments, and quick actions.",
         "由 AI 为快速对话、你来我往的争论与快捷行动而触发。", "once"),
        (">FULL RENDER</div>", ">完整渲染</div>", "once"),
        ("Triggered by the AI for scene changes, deep immersion, and major plot events.",
         "由 AI 为场景切换、深度沉浸与重大剧情事件而触发。", "once"),
        (">Language Output</div>", ">语言输出</div>", "once"),
        ("Leave empty for default (English)", "留空则使用默认（英语）", "once"),
        ('placeholder="e.g. Arabic, French…"', 'placeholder="例如：阿拉伯语、法语…"', "once"),
        (">User Gender</div>", ">用户性别</div>", "once"),
        ("Ensure the AI addresses you correctly", "确保 AI 正确称呼你", "once"),
        (">Off</option>", ">关闭</option>", "once"),
        (">Male (Him/He)</option>", ">男性（他）</option>", "once"),
        (">Female (Her/She)</option>", ">女性（她）</option>", "once"),
        ("> Gameplay Add-ons</div>", "> 玩法附加组件</div>", "once"),
        ("<span>Pick the three or four you actually want, not all of them. Every add-on is another\n            system the model has to hold in mind while it writes, and past a handful the prose\n            thins out as the attention goes into bookkeeping. Fewer, chosen on purpose, reads better.</span>",
         "<span>只挑你真正想要的三四个，而不是全部。每个附加组件都是模型写作时必须记在心上的又一套系统，超过一定数量后，注意力转向记账，行文就会变薄。少而精，读起来更好。</span>", "once"),
        (">Cinematic Sounds</span>", ">影视音效</span>", "once"),
        ("Force the AI to use precise phonetic sound words (e.g., click, thud) instead of abstract descriptions.",
         "强制 AI 使用精确的拟声词（例如 click、thud）而非抽象描述。", "once"),
        (">Animate Sounds</div>", ">动态音效</div>", "once"),
        ("Wrap in HTML tags. For capable AI only.", "用 HTML 标签包裹。仅限能力足够的 AI。", "once"),
        ("Custom Module →", "自定义模块 →", "once"),
        ("> Output Formats</div>", "> 输出格式</div>", "once"),
        ("> Engine Override</span>", "> 引擎覆盖</span>", "once"),
    ],
    # ═══════════════════════════ globalSettings.js ═══════════════════════════
    "src/ui/tabs/globalSettings.js": [
        ("<h2>Global Settings</h2>", "<h2>全局设置</h2>", "once"),
        ("<p>Preferences that apply to every character and every chat.</p>",
         "<p>适用于每个角色与每个聊天的偏好设置。</p>", "once"),
        ("> Saved globally", "> 已全局保存", "once"),
        ("> Prompt Payload Preview</div>", "> 提示词载荷预览</div>", "once"),
        ("Shows the finished prompt in a popup before it is sent, so you can read exactly what the AI receives. Cancelling the popup stops the generation.",
         "在发送前于弹窗中展示最终提示词，让你能确切读到 AI 将收到什么。取消弹窗会停止生成。", "once"),
        ("> Utility Prefills</div>", "> 工具预填</div>", "once"),
        ("Puts an opening &lt;think&gt; into the AI's mouth for background jobs — Image Gen, the Ban List, the Story Director, NPC scans. <b>Off by default:</b> Claude and several other APIs reject a prefill outright. Turn it on only if yours accepts one.",
         "为后台任务——图像生成、屏蔽列表、故事导演、NPC 扫描——在 AI 口中放入一个起始 &lt;think&gt;。<b>默认关闭：</b>Claude 与其他多个 API 会直接拒绝预填。只有你的 API 接受时才开启。", "once"),
        ("> Profile Save Mode</div>", "> 档案保存模式</div>", "once"),
        ("<b>Per Character</b> shares your settings across every chat with that character. <b>Per Chat</b> keeps each chat and each branch on its own settings.",
         "<b>按角色</b>将你的设置共享到与该角色的每个聊天。<b>按聊天</b>让每个聊天与每条分支各自保有设置。", "once"),
        (">Per Character (Default)</option>", ">按角色（默认）</option>", "once"),
        (">Per Chat</option>", ">按聊天</option>", "once"),
        ("> Send me a card</div>", "> 向我推荐一张角色卡</div>", "once"),
        ("Got a card or a scenario worth playing?", "有值得一玩的角色卡或场景吗？", "once"),
        ("I have been running out of things to roleplay, so I am collecting recommendations. Attach a character card, describe a scenario, or just drop a link to something you enjoyed. <b>Completely anonymous</b> — no sign-in, no name, nothing tying it back to you. I cannot reply, so say everything you want to say in the form.",
         "我最近缺角色扮演的素材，所以在收集推荐。附上一张角色卡、描述一个场景，或直接丢一个你喜欢的链接。<b>完全匿名</b>——无需登录、不留姓名，也没有任何会关联到你的信息。我无法回复，所以请在表单里把想说的话都说出来。", "once"),
        ("> Open the form", "> 打开表单", "once"),
        ("Opens tally.so in your browser, outside SillyTavern.",
         "在 SillyTavern 之外的浏览器中打开 tally.so。", "once"),
        ("<b>GitHub</b><small>Source, issues and releases</small>",
         "<b>GitHub</b><small>源码、问题与发布</small>", "once"),
        ("Save mode changed to Per ${gs.saveMode === 'chat' ? 'Chat' : 'Character'}.",
         "保存模式已改为按${gs.saveMode === 'chat' ? '聊天' : '角色'}。", "once"),
    ],
    # ═══════════════════════════ personality.js ═══════════════════════════
    "src/ui/tabs/personality.js": [
        ("<h2>Persona</h2>", "<h2>人设</h2>", "once"),
        ("<p>Set the narrator's voice and fine‑tune engine behavior.</p>",
         "<p>设置叙述者的声音并微调引擎行为。</p>", "once"),
        ("? 'Locked' : localProfile.personality", "? '已锁定' : localProfile.personality", "once"),
        ("<h3>Persona Locked</h3>", "<h3>人设已锁定</h3>", "once"),
        ("${lockedEngineName} manages its own internal persona and strictly enforces narrative toggles natively. Standard injections are completely disabled.",
         "${lockedEngineName} 管理自己内部的人设，并原生严格执行叙事开关。标准注入被完全禁用。", "once"),
        ("<h3>Persona Selection Locked</h3>", "<h3>人设选择已锁定</h3>", "all"),
        ("The V6 Dream Team engine utilizes an intrinsic 6-specialist framework. Standard persona injections are disabled to prevent logic conflicts.",
         "V6 Dream Team 引擎采用内在的 6 专家框架。标准人设注入被禁用，以防逻辑冲突。", "once"),
        ("The V7 engine utilizes a pure narrative framework. Standard persona injections are disabled to prevent logic conflicts.",
         "V7 引擎采用纯粹的叙事框架。标准人设注入被禁用，以防逻辑冲突。", "once"),
        ('"megumin": "A rebellious, dominant voice. Adds an edge of arrogance and chaos to the narration. Best for energetic or confrontational stories."',
         '"megumin": "叛逆、强势的声音。为旁白添一分傲慢与混乱的锋芒。最适合充满活力或对抗性的故事。"', "once"),
        ('"director": "Professional narrator. Clean, authoritative story direction with cinematic awareness."',
         '"director": "专业叙述者。干净、权威的故事导演，带有电影化意识。"', "once"),
        ('"Nora": "Nora should i say more."', '"Nora": "Nora，还用多说吗。"', "once"),
        ('"engine": "No personality overlay at all. The engine speaks in its purest form — precise, neutral, and fully under your control. Recommended for most setups."',
         '"engine": "完全没有性格叠加。引擎以最纯粹的形式发声——精准、中立、完全受你掌控。推荐用于大多数配置。"', "once"),
        ("> Select Persona</div>", "> 选择人设</div>", "once"),
        ("> Recommended</span>", "> 推荐</span>", "once"),
        ("> Active</span>", "> 使用中</span>", "once"),
        ("> Extra Toggles</div>", "> 额外开关</div>", "once"),
        ("Off by default — most engines handle this natively",
         "默认关闭——大多数引擎原生支持", "once"),
    ],
    # ═══════════════════════════ sidePanelTab.js ═══════════════════════════
    "src/ui/tabs/sidePanelTab.js": [
        ("? 'Enabled' : 'Disabled'}", "? '已启用' : '已禁用'}", "once"),
        ("<h2>Side Panel</h2>", "<h2>侧边面板</h2>", "once"),
        ("<p>Dockable / floatable tracker panel. Drag it by the header when floating, resize from the edge, reorder sections. Updates automatically as the AI replies.</p>",
         "<p>可停靠 / 可浮动的追踪面板。浮动时拖拽标题栏移动、从边缘调整大小、为区块排序。AI 回复时自动更新。</p>", "once"),
        ("<strong>Discontinued.</strong> Blocks do this better &mdash; a nicer card, far more",
         "<strong>已停止开发。</strong>信息块做得更好——更漂亮的卡片、远多的", "once"),
        ("you can change about it, and it keeps up with new blocks as they land. And frankly,",
         "可改项，并且能跟上不断上线的新信息块。坦率地说，", "once"),
        ("Kazuma doesn't like the side panel.", "Kazuma 不喜欢侧边面板。", "once"),
        ("<br><br>So it is no longer being developed and has not kept up: newer blocks, custom",
         "<br><br>因此它已不再开发、也未跟上进度：新信息块、自定义", "once"),
        ("blocks and the stat blocks may not appear in it, or may appear wrong. It still works for",
         "信息块与状态块可能不会出现在其中，或显示错误。它仍能处理", "once"),
        ("what it already knew about, and everything it shows is drawn in the chat card",
         "它原本认识的内容，而且它显示的一切都会画进聊天卡片，", "once"),
        ("regardless.</span>", "无论如何。</span>", "once"),
        ("> Enable Side Panel</div>", "> 启用侧边面板</div>", "once"),
        ("Mounts the panel on the page. When off, trackers stay inline in the chat as usual.",
         "将面板挂载到页面上。关闭时，追踪器照常保持在聊天气泡内。", "once"),
        (">Mode</div>", ">模式</div>", "once"),
        ("Docked pins the panel to a screen edge; Floating turns it into a draggable, resizable window.",
         "停靠将面板固定到屏幕边缘；浮动则将其变为可拖拽、可调整大小的窗口。", "once"),
        (">Docked</option>", ">停靠</option>", "once"),
        (">Floating</option>", ">浮动</option>", "once"),
        (">Docked edge</div>", ">停靠边缘</div>", "once"),
        ("Which edge of the screen the panel anchors to.", "面板锚定到屏幕的哪条边缘。", "once"),
        (">Right</option>", ">右侧</option>", "once"),
        (">Left</option>", ">左侧</option>", "once"),
        (">Docked width</div>", ">停靠宽度</div>", "once"),
        ("You can also drag the panel's inner edge to resize. Mobile clamps to 94% of viewport.",
         "你也可以拖拽面板内缘调整大小。移动端限制为视口的 94%。", "once"),
        (">UI scale</div>", ">界面缩放</div>", "once"),
        ("Zoom the whole panel — text, cards, avatars, everything.",
         "缩放整个面板——文本、卡片、头像，一切。", "once"),
        (">Reset floating position</div>", ">重置浮动位置</div>", "once"),
        ("Brings a lost floating panel back on screen at the default spot and size.",
         "把丢失的浮动面板恢复到默认位置与大小。", "once"),
        ('fa-solid fa-crosshairs"></i> Reset</button>', 'fa-solid fa-crosshairs"></i> 重置</button>', "once"),
        ('fa-solid fa-rotate-left"></i> Reset</button>', 'fa-solid fa-rotate-left"></i> 重置</button>', "once"),
        (">Sections to show</div>", ">要显示的区块</div>", "once"),
        ("Toggle visibility. Numbers show current panel order — Alt+↑/↓ on a section's grip (in the panel) reorders it.",
         "切换可见性。数字显示当前面板顺序——在面板中按住 Alt+↑/↓ 拖动区块手柄可重新排序。", "once"),
        (">Hide sections with no data</div>", ">隐藏无数据的区块</div>", "once"),
        ("Sections with nothing to show disappear instead of rendering an empty shell.",
         "没有任何内容的区块会消失，而非渲染一个空壳。", "once"),
        (">Reset section layout</div>", ">重置区块布局</div>", "once"),
        ("Restores default order, visibility, and open/closed states.",
         "恢复默认顺序、可见性与展开/折叠状态。", "once"),
        (">Enable Present Characters Bar</div>", ">启用在场角色栏</div>", "once"),
        ("A Doom-style horizontal portrait strip next to the chat input. Pulls the cast from the AI's World State NPCs Present, portraits from the NPC Bank.",
         "聊天输入框旁的毁灭战士风格横向头像条。从 AI 世界状态的“在场 NPC”拉取阵容，从 NPC 库拉取头像。", "once"),
        (">Bar position</div>", ">栏位置</div>", "once"),
        ("Where the strip mounts relative to SillyTavern's message input.",
         "该条带相对 SillyTavern 消息输入框的挂载位置。", "once"),
        (">Above input</option>", ">输入框上方</option>", "once"),
        (">Below input</option>", ">输入框下方</option>", "once"),
        (">Off (hide)</option>", ">关闭（隐藏）</option>", "once"),
        (">Card size</div>", ">卡片尺寸</div>", "once"),
        ("Width × height of each portrait card in the strip.",
         "条带中每张头像卡的宽 × 高。", "once"),
        ("> Advanced</div>", "> 高级</div>", "once"),
        (">Hide inline tracker blocks in chat</div>", ">隐藏聊天中的行内追踪信息块</div>", "once"),
        ("Removes the <code>&lt;details&gt;</code> tracker blocks from the rendered chat DOM (they stay in the saved message so re-parsing keeps working).",
         "从渲染出的聊天 DOM 中移除 <code>&lt;details&gt;</code> 追踪信息块（它们仍保留在已保存消息中，因此重新解析仍可工作）。", "once"),
        (">Force refresh</div>", ">强制刷新</div>", "once"),
        ("Re-parse the latest assistant message and rebuild the panel right now.",
         "立即重新解析最新一条助手消息并重建面板。", "once"),
        ("> Refresh</button>", "> 刷新</button>", "once"),
        (">Reset all side-panel settings</div>", ">重置全部侧边面板设置</div>", "once"),
        ("Wipes every setting on this tab back to defaults. Debug console handle: <code>window.LukaSuite</code>",
         "将此标签页上的所有设置擦除并恢复默认值。调试控制台句柄：<code>window.LukaSuite</code>", "once"),
        ("> Reset all</button>", "> 全部重置</button>", "once"),
        ("> Enabled`", "> 已启用`", "once"),
        ("> Disabled`", "> 已禁用`", "once"),
        ('"Floating position reset"', '"浮动位置已重置"', "once"),
        ('"Section layout reset"', '"区块布局已重置"', "once"),
        ('"Side panel refreshed"', '"侧边面板已刷新"', "once"),
        ("Reset ALL side-panel settings to defaults?", "重置全部侧边面板设置并恢复默认值？", "once"),
        ('"Side-panel settings reset"', '"侧边面板设置已重置"', "once"),
    ],
    # ═══════════════════════════ devmode.js ═══════════════════════════
    "src/ui/devmode.js": [
        ('{ text: "Off", cls: "st-off" }', '{ text: "关闭", cls: "st-off" }', "once"),
        ('{ text: "Automatic", cls: "st-auto" }', '{ text: "自动", cls: "st-auto" }', "once"),
        ('{ text: "Edited", cls: "st-custom" }', '{ text: "已编辑", cls: "st-custom" }', "once"),
        ('{ text: "Using default", cls: "st-default" }', '{ text: "使用默认", cls: "st-default" }', "once"),
        ('{ text: "Empty", cls: "st-empty" }', '{ text: "空", cls: "st-empty" }', "once"),
        ('"after the whole chat history — one of the last things the model reads"',
         '"位于整段聊天历史之后——模型最后读取的内容之一"', "once"),
        ('"before the chat history"', '"位于聊天历史之前"', "once"),
        (">Use the shared version</button>", ">使用共享版本</button>", "once"),
        ('placeholder="Empty — nothing is added at this point in the prompt."',
         'placeholder="空——提示词此处不添加任何内容。"', "once"),
        ('label: "Built-in default", value: slot.fallback', 'label: "内置默认", value: slot.fallback', "once"),
        ("> Reset to default</button>", "> 重置为默认</button>", "once"),
        ("> Clear</button>", "> 清空</button>", "once"),
        ("saved for every engine.", "已为每个引擎保存。", "once"),
        ("is back to the built-in version.", "已恢复为内置版本。", "once"),
        ("<label>What should this be called?</label>", "<label>如何命名此模块？</label>", "once"),
        ('placeholder="e.g. Extra combat detail"', 'placeholder="例如：额外的战斗细节"', "once"),
        ("<label>Which tab should its on/off switch live in?</label>",
         "<label>其开关应位于哪个标签页？</label>", "once"),
        (">Add-ons tab</option>", ">附加组件页</option>", "once"),
        (">Global tab</option>", ">全局页</option>", "once"),
        ("<label>The text to add</label>", "<label>要添加的文本</label>", "once"),
        ('? "Edit module" : "Add module"', '? "编辑模块" : "添加模块"', "once"),
        ('{ okButton: "Save", cancelButton: "Cancel", wide: true }',
         '{ okButton: "保存", cancelButton: "取消", wide: true }', "once"),
        ("A module with no text would do nothing, so it was not added.",
         "没有文本的模块不会起任何作用，因此未添加。", "once"),
        ('switch in ${mod.location === "addons" ? "Global" : "Add-ons"}',
         '开关位于${mod.location === "addons" ? "全局页" : "附加组件页"}', "once"),
        ('title="Edit"', 'title="编辑"', "once"),
        ('title="Remove"', 'title="移除"', "once"),
        ("Remove <b>${esc(mod.name)}</b> from this engine?",
         "从该引擎中移除 <b>${esc(mod.name)}</b>？", "once"),
        ('"Remove module", { okButton: "Remove", cancelButton: "Keep" }',
         '"移除模块", { okButton: "移除", cancelButton: "保留" }', "once"),
        ("> Add your own text here</button>", "> 在此添加你自己的文本</button>", "once"),
        ('"Change what the AI is told, and see exactly where each piece lands."',
         '"修改 AI 被告知的内容，并精确查看每块落在哪里。"', "once"),
        ("<b>You're running a Cache Friendly preset.</b> The Engines document shows the",
         "<b>你正在使用 Cache Friendly 预设。</b>引擎文档展示了", "once"),
        ("standard card order. Several tags sit further down in Output RULES in this preset.",
         "标准卡片顺序。该预设中部分标签位于 Output RULES 更靠后的位置。", "all"),
        ("Don't worry &mdash; editing works exactly the same.</span>",
         "别担心——编辑方式完全相同。</span>", "all"),
        (">Add-ons</div>", ">附加组件</div>", "once"),
        ("The pieces every engine shares — thinking steps, MVU, the ban list,",
         "每个引擎共享的部分——思考步骤、MVU、屏蔽列表、", "once"),
        ("death and combat, the output blocks.", "死亡与战斗、输出信息块。", "once"),
        ("<b>Change one here and every engine uses it.</b>",
         "<b>在这里修改一处，所有引擎都会使用。</b>", "once"),
        ("${changed} changed", "${changed} 处已修改", "once"),
        ("${meguminAddonSlots().length} to choose from",
         "可从 ${meguminAddonSlots().length} 个中选择", "once"),
        (">Open <i class=\"fa-solid fa-arrow-right\"></i></div>", ">打开 <i class=\"fa-solid fa-arrow-right\"></i></div>", "all"),
        (">Engines</div>", ">引擎</div>", "once"),
        ("The rules that make one engine write differently from another.",
         "让一个引擎与另一个引擎写作方式不同的规则。", "once"),
        ("Shown as the real prompt, in the real order, with your add-ons marked",
         "以真实提示词、按真实顺序展示，并标注你的附加组件", "once"),
        ("where they land.", "落在何处。", "once"),
        ("${engines} of your own", "你自己的 ${engines} 个", "once"),
        ('"start from a built-in one"', '"从内置引擎开始"', "once"),
        ('"Shared by every engine. Pick one to edit it and see where it goes."',
         '"所有引擎共享。选一个来编辑，看看它落在哪里。"', "once"),
        ('backBar("Add-ons"', 'backBar("附加组件"', "once"),
        ("> your version</span>", "> 你的版本</span>", "once"),
        ("That add-on no longer exists.", "该附加组件已不存在。", "once"),
        ('? "Back to engine" : "All add-ons"', '? "返回引擎" : "所有附加组件"', "once"),
        ("> Where this goes</div>", "> 它落在哪里</div>", "once"),
        ("Positions shown come from the standard preset. On Cache Friendly a few tags",
         "显示的位置来自标准预设。在 Cache Friendly 中，部分标签", "once"),
        ("sit further down, in Output RULES.", "位于更靠后的 Output RULES 中。", "once"),
        ('"An engine is the set of rules telling the AI how to write."',
         '"引擎是告诉 AI 如何写作的一套规则。"', "once"),
        ('backBar("Engines"', 'backBar("引擎"', "once"),
        ("> Create Blank Engine</button>", "> 创建空白引擎</button>", "once"),
        ("> Import Engine (JSON)</button>", "> 导入引擎（JSON）</button>", "once"),
        ("Imported ${imported.label}!", "已导入 ${imported.label}！", "once"),
        ('"Invalid JSON file."', '"JSON 文件无效。"', "once"),
        ("> Your Engines</div>", "> 你的引擎</div>", "once"),
        ("None yet. Pick a built-in one below to start from.",
         "还没有。从下方选择一个内置引擎开始。", "once"),
        ("Copy of ${esc(m.parentId)}", "${esc(m.parentId)} 的副本", "once"),
        ('"Your own engine"', '"你自己的引擎"', "once"),
        ('title="Export"', 'title="导出"', "once"),
        ('fa-pen"></i> Edit</button>', 'fa-pen"></i> 编辑</button>', "once"),
        ('title="Delete"', 'title="删除"', "once"),
        ("Delete <b>${esc(m.label)}</b>? This cannot be undone.<br><br>Your add-ons are not affected.",
         "删除 <b>${esc(m.label)}</b>？此操作无法撤销。<br><br>你的附加组件不受影响。", "once"),
        ('"Delete engine", { okButton: "Delete", cancelButton: "Keep" }',
         '"删除引擎", { okButton: "删除", cancelButton: "保留" }', "once"),
        ("> Start From A Built-In Engine</div>", "> 从内置引擎开始</div>", "once"),
        ("Built in. Makes you an editable copy.", "内置引擎。为你生成一份可编辑副本。", "once"),
        ("> Make A Copy</button>", "> 制作副本</button>", "once"),
        ("> This engine</span>", "> 该引擎</span>", "once"),
        ("SillyTavern fills this in", "由 SillyTavern 自动填充", "once"),
        ("Unrecognised slot", "无法识别的插槽", "once"),
        ("The preset asks for ${esc(seg.trigger)}, but the extension has no entry for it.",
         "预设要求 ${esc(seg.trigger)}，但扩展没有对应的条目。", "once"),
        (">Other engine settings</span>", ">其他引擎设置</span>", "once"),
        ('"The real prompt, in the real order. Gold panels belong to this engine; green ones are shared add-ons."',
         '"真实提示词，按真实顺序排列。金色面板属于该引擎；绿色为共享附加组件。"', "once"),
        ("> Back</button>", "> 返回</button>", "once"),
        ("> Show automatic parts", "> 显示自动生成的部分", "once"),
        ("> Save Engine</button>", "> 保存引擎</button>", "once"),
        ("> This engine — needs Save</span>", "> 该引擎 — 需要保存</span>", "once"),
        ("> Add-on — click to edit, shared by all</span>", "> 附加组件 — 点击编辑，所有引擎共享</span>", "once"),
        ("> Automatic — filled in for you</span>", "> 自动 — 为你自动填充</span>", "once"),
        ("This engine has changes you have not saved. Leave anyway?<br><br>",
         "该引擎有你尚未保存的更改。仍要离开？<br><br>", "once"),
        ("Add-ons are already saved — only this engine's own gold panels would be lost.",
         "附加组件已保存——只有该引擎自己的金色面板会丢失。", "once"),
        ('"Unsaved changes", { okButton: "Discard", cancelButton: "Stay" }',
         '"未保存的更改", { okButton: "丢弃", cancelButton: "留下" }', "once"),
        ('"Engine saved."', '"引擎已保存。"', "once"),
        ("> Exit Dev", "> 退出开发模式", "once"),
        ('label: "New Custom Engine"', 'label: "新自定义引擎"', "once"),
        ('modeData.label = core.label + " (Copy)"', 'modeData.label = core.label + "（副本）"', "once"),
        ("That engine no longer exists.", "该引擎已不存在。", "once"),
    ],
    # ═══════════════════════════ progress.js / promptEditor.js ═══════════════════════════
    "src/ui/progress.js": [
        (">Generating Image...</span>", ">正在生成图像...</span>", "once"),
        ('text = "Processing..."', 'text = "正在处理..."', "once"),
    ],
    "src/ui/promptEditor.js": [
        ('title="Reset to default"', 'title="重置为默认"', "once"),
        ("> Reset</button>", "> 重置</button>", "once"),
        ('title="Enable custom prompts override"', 'title="启用自定义提示词覆盖"', "once"),
        ("> Reset All Defaults</button>", "> 全部重置为默认</button>", "once"),
    ],
}
