#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Megumin-Suite 中文本地化 映射批 4d：图像生成 + 记忆核心（核心 UI 项）"""

MAPS = {
    # ═══════════════════════════ imagegen/index.js ═══════════════════════════
    "src/features/imagegen/index.js": [
        ("<h2>Image Generation</h2>", "<h2>图像生成</h2>", "once"),
        ("<p>ComfyUI integration for automatic scene rendering.</p>",
         "<p>用于自动场景渲染的 ComfyUI 集成。</p>", "once"),
        ("? 'Enabled' : 'Disabled'}", "? '已启用' : '已禁用'}", "once"),
        ("<strong>New to this? There's a setup guide.</strong> Getting ComfyUI talking to",
         "<strong>第一次用？这里有设置指南。</strong>让 ComfyUI 与", "once"),
        ("SillyTavern is the hard part, and none of the settings below matter until it is.",
         "SillyTavern 通话是最难的部分，在此之前下方设置都无关紧要。", "once"),
        (">Read the walkthrough</a> — it covers", ">阅读教程</a>——它涵盖", "once"),
        ("the install, the connection and the first working image.",
         "安装、连接与第一张成功生成的图像。", "once"),
        ("> Enable Image Generation</div>", "> 启用图像生成</div>", "once"),
        ("Activate ComfyUI integration for this specific character/group.",
         "为此角色/群组激活 ComfyUI 集成。", "once"),
        ("> Prompt Generator Backend</div>", "> 提示词生成后端</div>", "once"),
        (">Generation Method</div>", ">生成方式</div>", "once"),
        ('"Direct" is faster. "Megumin Image" is more creative.',
         '“直接”更快。“Megumin 图像”更有创意。', "once"),
        (">Direct API Call (Fast)</option>", ">直接 API 调用（快速）</option>", "once"),
        (">Megumin Image Preset</option>", ">Megumin 图像预设</option>", "once"),
        ("> ComfyUI Server & Workflow</div>", "> ComfyUI 服务器与工作流</div>", "once"),
        ("> Test</button>", "> 测试</button>", "once"),
        ('title="New Workflow"', 'title="新建工作流"', "once"),
        ('title="Edit JSON"', 'title="编辑 JSON"', "once"),
        ('title="Delete"', 'title="删除"', "once"),
        ("> Triggers & Formatting</div>", "> 触发与格式</div>", "once"),
        (">Trigger Mode</div>", ">触发模式</div>", "once"),
        (">Always (Every Reply)</option>", ">始终（每条回复）</option>", "once"),
        (">After X Replies</option>", ">每 X 条回复</option>", "once"),
        (">Only when character sends a pic</option>", ">仅当角色发送图片时</option>", "once"),
        (">Manual Button Only</option>", ">仅手动按钮</option>", "once"),
        (">Inject Mode</div>", ">注入模式</div>", "once"),
        (">New Message (Gallery)</option>", ">新消息（画廊）</option>", "once"),
        (">Inline (Inside AI Reply)</option>", ">行内（AI 回复内）</option>", "once"),
        (">Image Count</div>", ">图像数量</div>", "once"),
        (">1 Image</option>", ">1 张图像</option>", "once"),
        (">2 Images</option>", ">2 张图像</option>", "once"),
        (">3 Images</option>", ">3 张图像</option>", "once"),
        (">4 Images</option>", ">4 张图像</option>", "once"),
        (">Every X Replies</div>", ">每 X 条回复</div>", "once"),
        ("Preview Prompt Before Sending", "发送前预览提示词", "once"),
        ("Show a popup to view or edit the AI's prompt before rendering.",
         "渲染前弹出窗口，查看或编辑 AI 的提示词。", "once"),
        (">Prompt Template</div>", ">提示词模板</div>", "once"),
        ("Include Examples <i class=\"fa-solid fa-circle-question\"",
         "包含示例 <i class=\"fa-solid fa-circle-question\"", "once"),
        ('title="Make the image prompt better but increase input token."',
         'title="让图像提示词更好，但会增加输入 token。"', "once"),
        ("Better Booru tags <i class=\"fa-solid fa-circle-question\"",
         "更好的 Booru 标签 <i class=\"fa-solid fa-circle-question\"", "once"),
        ('title="It may increase empty responses."', 'title="可能增加空回复。"', "once"),
        ("Inject NPC Tags <i class=\"fa-solid fa-circle-question\"",
         "注入 NPC 标签 <i class=\"fa-solid fa-circle-question\"", "once"),
        ('title="Automatically attach saved NPC image tags to the prompt if they are in the scene."',
         'title="如果 NPC 在场景中，自动将其已保存的图像标签附加到提示词。"', "once"),
        ('placeholder="Extra Instructions (e.g. moody lighting, dark atmosphere...)"',
         'placeholder="额外指令（例如：忧郁的灯光、黑暗氛围...）"', "once"),
        ("> Image Parameters</div>", "> 图像参数</div>", "once"),
        (">Loading Models...</option>", ">正在加载模型...</option>", "once"),
        (">Loading Samplers...</option>", ">正在加载采样器...</option>", "once"),
        (">Resolution Preset</div>", ">分辨率预设</div>", "once"),
        (">Seed (-1 for random)</div>", ">种子（-1 为随机）</div>", "once"),
        ('title="Set to Random (-1)"', 'title="设为随机（-1）"', "once"),
        (">Negative Prompt Override</div>", ">负面提示词覆盖</div>", "once"),
        (">Positive Prefix (Auto-Added to Front)</div>", ">正面前缀（自动添加到开头）</div>", "once"),
        ("> LoRA Lab</div>", "> LoRA 实验室</div>", "once"),
        (">Slot ${i}</div>", ">插槽 ${i}</div>", "once"),
        (">Loading...</option>", ">正在加载...</option>", "once"),
        ('placeholder="Trigger words..."', 'placeholder="触发词..."', "once"),
        ('title="Words automatically injected into the prompt when this LoRA is active."',
         'title="此 LoRA 激活时自动注入提示词的词语。"', "once"),
        ('title: "Advanced: Edit Prompts"', 'title: "高级：编辑提示词"', "once"),
        ("-- Select Preset --", "-- 选择预设 --", "once"),
        ("`Restored settings for ${newWorkflow}`", "`已恢复 ${newWorkflow} 的设置`", "once"),
        ("`New workflow context active`", "`新工作流上下文已激活`", "once"),
        ("-- Select Model --", "-- 选择模型 --", "once"),
        ("-- No LoRA --", "-- 无 LoRA --", "once"),
        ('"ComfyUI Connected!"', '"ComfyUI 已连接！"', "once"),
        ('"Connection Failed: "', '"连接失败："', "once"),
        ("Failed to load", "加载失败", "all"),
        ('prompt("New workflow file name (e.g. \'my_flux.json\'):")',
         'prompt("新工作流文件名（例如 \'my_flux.json\'）：")', "once"),
        ('"Workflow created!"', '"工作流已创建！"', "once"),
        ('`Delete ${name}?`', '`删除 ${name}？`', "once"),
        ('"Deleted."', '"已删除。"', "once"),
        ('"No workflow selected"', '"未选择工作流"', "once"),
        ("加载失败 file. Starting empty.", "加载文件失败，从空白开始。", "once"),
        ('title="Beautify JSON"', 'title="美化 JSON"', "once"),
        ("> Format</button>", "> 格式化</button>", "once"),
        ('title="Upload .json file"', 'title="上传 .json 文件"', "once"),
        ("> Import</button>", "> 导入</button>", "once"),
        ('title="Download .json file"', 'title="下载 .json 文件"', "once"),
        ("> Export</button>", "> 导出</button>", "once"),
        (">Placeholders</h4>", ">占位符</h4>", "once"),
        ('"Formatted"', '"已格式化"', "once"),
        ('"Invalid JSON"', '"无效的 JSON"', "once"),
        ('"Imported"', '"已导入"', "once"),
        ('"Invalid content"', '"内容无效"', "once"),
        ("okButton: 'Save Changes', cancelButton: 'Cancel'",
         "okButton: '保存更改', cancelButton: '取消'", "once"),
        ('"Workflow Saved!"', '"工作流已保存！"', "once"),
        ('"Save Failed."', '"保存失败。"', "once"),
        ('"Analyzing Scene..."', '"正在分析场景..."', "once"),
        ('"Sending to ComfyUI..."', '"正在发送到 ComfyUI..."', "once"),
        ('"Manual generation failed."', '"手动生成失败。"', "once"),
        ("'Regenerate this image'", "'重新生成此图像'", "once"),
        ('"Image Generation is disabled."', '"图像生成已禁用。"', "once"),
        ('"Could not find the original message for this image."',
         '"找不到此图像的原始消息。"', "once"),
        ("[Regenerating Image...]", "[正在重新生成图像...]", "once"),
        ('"Could not find the original image block to replace."',
         '"找不到要替换的原始图像信息块。"', "once"),
        ('"Regenerating inline image..."', '"正在重新生成行内图像..."', "once"),
        ("Review or modify the prompt before it goes to ComfyUI.",
         "在发送到 ComfyUI 之前查看或修改提示词。", "once"),
        ('"Preview Image Prompt"', '"预览图像提示词"', "once"),
        ('okButton: "Send to ComfyUI"', 'okButton: "发送到 ComfyUI"', "once"),
        ('"Generation cancelled."', '"生成已取消。"', "once"),
        ('"Prompt cannot be empty."', '"提示词不能为空。"', "once"),
        ('"Preparing to Render..."', '"正在准备渲染..."', "once"),
        ('`Could not load ${s.currentWorkflowName}`', '`无法加载 ${s.currentWorkflowName}`', "once"),
        ('Rendering Image... ${value}/${max} (${pct}%)', '正在渲染图像... ${value}/${max}（${pct}%）', "once"),
        ('"Rendering Image..."', '"正在渲染图像..."', "once"),
        ('"Downloading..."', '"正在下载..."', "once"),
        ('"Image injected inline!"', '"图像已行内注入！"', "once"),
        ('"Gallery updated!"', '"画廊已更新！"', "once"),
        ('"Image inserted!"', '"图像已插入！"', "once"),
        ("[Image Generation Failed]", "[图像生成失败]", "once"),
        ("[Image Generation Failed: ${e.message}]", "[图像生成失败：${e.message}]", "once"),
        ('"Comfy Error: "', '"Comfy 错误："', "once"),
    ],
    # ═══════════════════════════ memory/index.js（核心 UI） ═══════════════════════════
    "src/features/memory/index.js": [
        ("<h2>Memory Core</h2>", "<h2>记忆核心</h2>", "once"),
        ("3-Tier Context Management: Working, Short-Term, and Long-Term Vector DB.",
         "三层上下文管理：工作记忆、短期记忆与长期向量库。", "once"),
        ("? 'Enabled' : 'Disabled'}", "? '已启用' : '已禁用'}", "once"),
        ("<strong>Before you switch this on, two things.</strong>",
         "<strong>开启之前，先说两件事。</strong>", "once"),
        ("It is not cache friendly.", "它不友好缓存。", "once"),
        ("Use Semantic Embeddings, not TF-IDF.", "使用语义嵌入，而非 TF-IDF。", "once"),
        ("> Enable Memory Core</div>", "> 启用记忆核心</div>", "once"),
        ("Archiving happens silently in the background. Old messages fade in the UI and are replaced in the prompt with injected summaries.",
         "归档在后台静默进行。旧消息在界面中淡出，并在提示词中被注入的摘要替换。", "once"),
        ("</i> Context Allocation Dashboard", "</i> 上下文分配仪表盘", "once"),
        ('title="Import Memory Core"', 'title="导入记忆核心"', "once"),
        ('title="Export Memory Core"', 'title="导出记忆核心"', "once"),
        ("</span> Tokens Saved", "</span> 已节省的 token", "once"),
        ("</i> Vault</span>", "</i> 记忆库</span>", "once"),
        ("color: #f59e0b; font-size: 0.5rem;\"></i> Short-Term", "color: #f59e0b; font-size: 0.5rem;\"></i> 短期", "once"),
        ("</i> Pending</span>", "</i> 待处理</span>", "once"),
        ("</i> Working</span>", "</i> 工作中</span>", "once"),
        ('title="Vaulted (Archived)"', 'title="已入库存档"', "once"),
        ('title="Short-Term (Summaries)"', 'title="短期（摘要）"', "once"),
        ('title="Pending (Active Raw)"', 'title="待处理（活跃原文）"', "once"),
        ('title="Working (Active Raw)"', 'title="工作中（活跃原文）"', "once"),
        ("&larr; Oldest (First Message)</span>", "&larr; 最旧（第一条消息）</span>", "once"),
        ("Newest (Last Message) &rarr;</span>", "最新（最后一条消息） &rarr;</span>", "once"),
        ("Monitoring Chat History...", "正在监控聊天历史...", "once"),
        ("> Extraction Engine Settings</div>", "> 提取引擎设置</div>", "once"),
        ("</i> How to Use</div>", "</i> 使用方法</div>", "once"),
        ("1- Choose your Memory Architecture and how much of each type you want (default is 30 raw, 70 summary).<br>",
         "1- 选择你的记忆架构以及每种类型想要多少（默认 30 原文、70 摘要）。<br>", "once"),
        ("2- Hit <b>Apply & Extract Pending</b> to save and start it.<br>",
         "2- 点击 <b>应用并提取待处理</b> 来保存并启动。<br>", "once"),
        ("3- You can choose between manual and auto. For manual, you have to hit <b>Apply & Extract Pending</b> to trigger it.",
         "3- 你可以选择手动或自动。手动模式下，需要点击 <b>应用并提取待处理</b> 来触发。", "once"),
        (">Memory Architecture</div>", ">记忆架构</div>", "once"),
        ("Configure how memory tiers are structured: Raw text, short-term summaries, and long-term vector database, or bypass summaries to save API usage.",
         "配置记忆层级结构：原文、短期摘要与长期向量数据库，或跳过摘要以节省 API 用量。", "once"),
        (">Raw Text + Short-Term Summaries + Vault</option>", ">原文 + 短期摘要 + 记忆库</option>", "once"),
        (">Raw Text + Vault Directly (Skip Summaries)</option>", ">原文 + 直接入库（跳过摘要）</option>", "once"),
        ("Working Limit</span>", "工作上限</span>", "once"),
        ("Number of recent messages kept in raw, unmodified text format in the prompt. High limits consume more active context space.",
         "在提示词中以未修改的原文格式保留的最近消息数。高上限会占用更多活跃上下文空间。", "once"),
        ("Short-Term Limit</span>", "短期上限</span>", "once"),
        ("Range of past messages to keep summarized. Summaries are automatically created in blocks and injected chronologically.",
         "需要保持摘要状态的过往消息范围。摘要会自动分批创建并按时间顺序注入。", "once"),
        ("Chunk Size</span>", "分块大小</span>", "once"),
        ("Smaller chunks = more granular summaries but more API calls. Larger chunks = fewer calls but coarser memory.",
         "更小的分块 = 更细粒度的摘要，但更多 API 调用。更大的分块 = 更少调用，但记忆更粗。", "once"),
        ("</i> Apply & Extract Pending", "</i> 应用并提取待处理", "once"),
        (">Generator Backend</div>", ">生成后端</div>", "once"),
        ("Bypass standard preset configs for fast direct API calls, or use defined Megumin engine settings for character-style summaries.",
         "绕过标准预设配置以进行快速直接 API 调用，或使用已定义的 Megumin 引擎设置生成角色风格摘要。", "once"),
        (">Direct API Call (Fast)</option>", ">直接 API 调用（快速）</option>", "once"),
        (">Megumin Engine Preset</option>", ">Megumin 引擎预设</option>", "once"),
        (">Vault Scanner Engine</div>", ">记忆库扫描引擎</div>", "once"),
        ("Select the retrieval engine for matching long-term memories. TF-IDF runs locally, while Semantic Embeddings use Vector Storage.",
         "选择用于匹配长期记忆的检索引擎。TF-IDF 在本地运行，语义嵌入使用向量存储。", "once"),
        (">TF-IDF Keyword Matcher</option>", ">TF-IDF 关键词匹配器</option>", "once"),
        (">Semantic Embeddings (ST Native API)</option>", ">语义嵌入（ST 原生 API）</option>", "once"),
        (">Auto-Trigger Mode</div>", ">自动触发模式</div>", "once"),
        ("Trigger background memory sweeps. 'Every Reply' checks after every message, wait-pooling messages until a full chunk accumulates.",
         "触发后台记忆清扫。“每条回复”会在每条消息后检查，将消息汇集等待，直到积累成完整分块。", "once"),
        (">Manual Only</option>", ">仅手动</option>", "once"),
        (">Every Reply</option>", ">每条回复</option>", "once"),
        (">Every N Replies</option>", ">每 N 条回复</option>", "once"),
        ("</i> Short-Term Memory", "</i> 短期记忆", "once"),
        ("</i> Clear All</button>", "</i> 全部清空</button>", "all"),
        ("> Long-Term Vault (Vector Storage)</span>", "> 长期记忆库（向量存储）</span>", "once"),
        ('placeholder="Search archived memories..."', 'placeholder="搜索已归档的记忆..."', "once"),
        ('title="See what memories the AI is retrieving right now"',
         'title="查看 AI 当前正在检索的记忆"', "once"),
        ("> Test Scanner</button>", "> 测试扫描器</button>", "once"),
        ('title="Delete all Vault Archives"', 'title="删除全部记忆库归档"', "once"),
        ('"Short-Term memory is already empty."', '"短期记忆已为空。"', "once"),
        ("Are you sure you want to delete ALL Short-Term Memory chunks? They will revert to 'Pending' status.",
         "确定要删除全部短期记忆分块吗？它们将恢复为“待处理”状态。", "once"),
        ('"Short-Term Memory cleared."', '"短期记忆已清空。"', "once"),
        ('"Invalid Memory Core file format."', '"记忆核心文件格式无效。"', "once"),
        ("Do you want to merge imported memories with your existing ones? (Click 'Cancel' to overwrite)",
         "是否将导入的记忆与现有记忆合并？（点击“取消”则覆盖）", "once"),
        ('"Memories imported successfully!"', '"记忆导入成功！"', "once"),
        ('"Failed to parse JSON file."', '"解析 JSON 文件失败。"', "once"),
        ('"Vault is already empty."', '"记忆库已为空。"', "once"),
        ("WARNING: Are you sure you want to permanently delete ALL Long-Term Vault archives? This cannot be undone.",
         "警告：确定要永久删除全部长期记忆库归档吗？此操作无法撤销。", "once"),
        ('"Long-Term Vault cleared."', '"长期记忆库已清空。"', "once"),
        ('title: "Advanced: Edit Prompts"', 'title: "高级：编辑提示词"', "once"),
        ('"Memory Core activated! Auto-archiving on every reply."',
         '"记忆核心已激活！将在每条回复时自动归档。"', "once"),
        ('Vector Database Synced! (${count} archive${count === 1 ? "" : "s"})',
         '向量数据库已同步！（${count} 条归档${count === 1 ? "" : "s"}）', "once"),
        ("Vector sync failed, see the console for the server response.",
         "向量同步失败，请查看控制台中的服务器响应。", "once"),
        ("Semantic mode is on, but the vault is empty — nothing to index yet.",
         "语义模式已开启，但记忆库为空——暂无内容可索引。", "once"),
        ("Semantic Mode active. Syncing vault to Vector Database...",
         "语义模式已激活。正在将记忆库同步到向量数据库...", "once"),
        ("Starting automatic extraction to fill new limits...",
         "正在启动自动提取以填充新的上限...", "once"),
        ("Vault is empty, so semantic mode has nothing to match yet.",
         "记忆库为空，语义模式暂无匹配内容。", "once"),
        ("Semantic Embeddings Engine Active</div>", "语义嵌入引擎已激活</div>", "once"),
        ("Using SillyTavern's Vector Storage API (LanceDB) to find the deep contextual meaning of the",
         "正在使用 SillyTavern 的向量存储 API（LanceDB）寻找以下内容的深层上下文含义：", "once"),
        ("No highly relevant memories found for the current context.</div>",
         "当前上下文没有找到高度相关的记忆。</div>", "once"),
        ("Vault Scanner Results", "记忆库扫描结果", "once"),
        ("No chunks generated yet. Generate chat messages to trigger background summarization.</div>",
         "尚未生成任何分块。生成聊天消息以触发后台摘要。</div>", "once"),
        ("You can manually edit this state extraction before it gets pushed to the Vector DB.</div>",
         "在推送到向量数据库之前，你可以手动编辑此状态提取。</div>", "once"),
        ('title="Delete Chunk"', 'title="删除分块"', "once"),
        ("Delete short-term memory chunk [Messages: ${chunk.id}]? It will be permanently removed.",
         "删除短期记忆分块 [Messages: ${chunk.id}]？它将被永久移除。", "once"),
        ("Load More (${remaining} remaining)", "加载更多（剩余 ${remaining}）", "all"),
        ("Vault is empty. Chunks automatically migrate here once they pass message ${passMsg}.</div>",
         "记忆库为空。分块在超过消息 ${passMsg} 后会自动迁移到这里。</div>", "once"),
        ('title="Delete Archive"', 'title="删除归档"', "once"),
        ('"Permanently delete this archived memory?"', '"永久删除这条已归档的记忆？"', "once"),
        ('"Not enough messages past the working limit to archive."',
         '"超过工作上限的消息数不足，无法归档。"', "once"),
        ('"All archives are up to date."', '"所有归档都是最新的。"', "once"),
        ("Preparing...`", "准备中...`", "once"),
        ("Processing ${idx + 1}/${totalChunks} (${percent}%)", "正在处理 ${idx + 1}/${totalChunks}（${percent}%）", "once"),
        ("Extracting State: Messages ${chunkData.id} (${idx + 1}/${totalChunks})...",
         "正在提取状态：Messages ${chunkData.id}（${idx + 1}/${totalChunks}）...", "once"),
        ("Archived ${bypassedCount} chunk(s) directly to Vault (bypassed AI).",
         "已将 ${bypassedCount} 个分块直接归档到记忆库（绕过 AI）。", "once"),
        ('"Syncing new Vault archives to Vector Database..."',
         '"正在将新的记忆库归档同步到向量数据库..."', "once"),
        ('"Archive Extraction Complete!"', '"归档提取完成！"', "once"),
        ('"Failed to generate memory summaries."', '"生成记忆摘要失败。"', "once"),
        ('${removedCount} archived block${removedCount === 1 ? "" : "s"} returned to the chat.',
         '${removedCount} 个已归档信息块已返回聊天。', "once"),
        ('"Megumin Suite — working set rebalanced"', '"Megumin Suite — 工作集已重新平衡"', "once"),
        ('"Limits Applied! Overlapping archives returned to chat."',
         '"已应用上限！重叠的归档已返回聊天。"', "once"),
        ('"Limits Applied. No overlaps found."', '"已应用上限。未发现重叠。"', "once"),
        ("Retrieved memories sit ahead of the\n            chat history in the prompt, so when what it retrieves changes, your provider re-reads the\n            whole history instead of serving it from cache.",
         "检索到的记忆会排在提示词中聊天记录之前，因此当检索内容变化时，提供商将重新读取\n            整段历史，而非命中缓存。", "once"),
        ("Keyword matching is the\n            fallback and it shows &mdash; semantic search finds the right archive far more often.",
         "关键词匹配只是兜底方案，效果显而易见&mdash;&mdash;语义搜索找到正确档案的几率要高得多。", "once"),
    ],
}
